tag @s add success
execute if entity @s[advancements={medabots_server:get_all_medabots/wave_1/blackstag={legs=false,left_arm=false,right_arm=false,head=false}}] run tag @s add out_of_stock
tellraw @s[tag=out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.not_available"}]}
tellraw @s[tag=!out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.medapart"}]}
tag @s remove out_of_stock
tellraw @s[advancements={medabots_server:get_all_medabots/wave_1/blackstag={legs=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 53"},"with":[{"translate":"medabots_server:entity.blackstag","extra":[{"text":" "},{"translate":"medabots_server:item.blackstag_blackfluke"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:get_all_medabots/wave_1/blackstag={left_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 54"},"with":[{"translate":"medabots_server:entity.blackstag","extra":[{"text":" "},{"translate":"medabots_server:item.blackstag_blackbeat"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:get_all_medabots/wave_1/blackstag={right_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 55"},"with":[{"translate":"medabots_server:entity.blackstag","extra":[{"text":" "},{"translate":"medabots_server:item.blackstag_blackvice"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:get_all_medabots/wave_1/blackstag={head=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 56"},"with":[{"translate":"medabots_server:entity.blackstag","extra":[{"text":" "},{"translate":"medabots_server:item.blackstag_blackincome"}]},{"text":"100"}]}
tag @s add final