# Bluesdog
summon minecraft:skeleton -1871 44 -555 {CustomName:"{\"translate\":\"medabots_server:entity.bluesdog\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/boxer/first_go/bluesdog",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["bluesdog","enemy_medabot","killerable","hostile","two_legged_legs","rifle_left_arm","rifle_right_arm","rifle_head","kabuto_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] Stage 79
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] Medabot 8
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] Battle 1
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] MaxHeadUses 18
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] MaxHeadArmor 60
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] MaxRightArmArmor 40
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] MaxLeftArmArmor 40
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] MaxLegsArmor 45
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] HeadPower 40
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] RightArmPower 16
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] LeftArmPower 20
scoreboard players set @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] LegsDefense 36
scoreboard players operation @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] MedabotNr 1
execute as @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1871,y=44,z=-555,distance=..1,tag=bluesdog] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1871 44 -555 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:8,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_howzer\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"45\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.bluesdog\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_howzer.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_howzer.model\"}"]},medabots_server:{id:"medabots_server:bluesdog_howzer",gender:0b,move:"two_legged",part:"legs",armor:45,defense:36,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1871 44 -555 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:8,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_battle_rifle\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.bluesdog\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_battle_rifle.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_battle_rifle.model\"}"]},medabots_server:{id:"medabots_server:bluesdog_battle_rifle",gender:0b,move:"rifle",part:"left_arm",armor:40,power:20,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1871 44 -555 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:8,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_aim_rifle\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.bluesdog\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_aim_rifle.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_aim_rifle.model\"}"]},medabots_server:{id:"medabots_server:bluesdog_aim_rifle",gender:0b,move:"rifle",part:"right_arm",armor:40,power:16,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1871 44 -555 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:8,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_headcannon\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"18\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"60\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.bluesdog\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_headcannon.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.bluesdog_headcannon.model\"}"]},medabots_server:{id:"medabots_server:bluesdog_headcannon",gender:0b,move:"rifle",part:"head",armor:60,power:40,uses:18,activated:0b,version:1}}}]}
execute positioned -1871 44 -555 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=bluesdog] MedabotNr

# Keithturtle
summon minecraft:skeleton -1916 44 -572 {CustomName:"{\"translate\":\"medabots_server:entity.keithturtle\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/boxer/first_go/keithturtle",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["keithturtle","enemy_medabot","killerable","hostile","tank_legs","laser_left_arm","laser_right_arm","laser_head","kabuto_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] Stage 79
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] Medabot 1
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] Battle 1
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] MaxHeadUses 5
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] MaxHeadArmor 50
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] MaxRightArmArmor 35
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] MaxLeftArmArmor 35
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] MaxLegsArmor 85
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] HeadPower 48
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] RightArmPower 23
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] LeftArmPower 29
scoreboard players set @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] LegsDefense 48
scoreboard players operation @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] MedabotNr 1
execute as @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1916,y=44,z=-572,distance=..1,tag=keithturtle] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1916 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:1,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_rollertank\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.tank\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.tank.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"85\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.keithturtle\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_rollertank.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_rollertank.model\"}"]},medabots_server:{id:"medabots_server:keithturtle_rollertank",gender:0b,move:"tank",part:"legs",armor:85,defense:48,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1916 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:1,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_gigalaser\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.laser\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.laser.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.keithturtle\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_gigalaser.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_gigalaser.model\"}"]},medabots_server:{id:"medabots_server:keithturtle_gigalaser",gender:0b,move:"laser",part:"left_arm",armor:35,power:29,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1916 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:1,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_megalaser\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.laser\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.laser.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.keithturtle\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_megalaser.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_megalaser.model\"}"]},medabots_server:{id:"medabots_server:keithturtle_megalaser",gender:0b,move:"laser",part:"right_arm",armor:35,power:23,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1916 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:1,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_tyranolaser\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.laser\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.laser.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"5\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"50\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.keithturtle\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_tyranolaser.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.keithturtle_tyranolaser.model\"}"]},medabots_server:{id:"medabots_server:keithturtle_tyranolaser",gender:0b,move:"laser",part:"head",armor:50,power:48,uses:5,activated:0b,version:1}}}]}
execute positioned -1916 44 -572 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=keithturtle] MedabotNr

# Peppercat
summon minecraft:skeleton -1873 43 -590 {CustomName:"{\"translate\":\"medabots_server:entity.peppercat\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/boxer/first_go/peppercat",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["peppercat","enemy_medabot","killerable","hostile","two_legged_legs","paralyze_left_arm","paralyze_right_arm","paralyze_head","kuwagata_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] Stage 79
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] Medabot 27
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] Battle 1
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] MaxHeadUses 7
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] MaxHeadArmor 60
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] MaxRightArmArmor 40
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] MaxLeftArmArmor 40
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] MaxLegsArmor 40
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] HeadPower 44
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] RightArmPower 24
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] LeftArmPower 28
scoreboard players set @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] LegsDefense 40
scoreboard players operation @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] MedabotNr 1
execute as @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1873,y=43,z=-590,distance=..1,tag=peppercat] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1873 43 -590 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:27,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_quick_alert\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.peppercat\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_quick_alert.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_quick_alert.model\"}"]},medabots_server:{id:"medabots_server:peppercat_quick_alert",gender:1b,move:"two_legged",part:"legs",armor:40,defense:40,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1873 43 -590 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:27,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_light_blow\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.paralyze\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.paralyze.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.peppercat\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_light_blow.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_light_blow.model\"}"]},medabots_server:{id:"medabots_server:peppercat_light_blow",gender:1b,move:"paralyze",part:"left_arm",armor:40,power:28,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1873 43 -590 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:27,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_lightjump\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.paralyze\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.paralyze.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.peppercat\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_lightjump.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_lightjump.model\"}"]},medabots_server:{id:"medabots_server:peppercat_lightjump",gender:1b,move:"paralyze",part:"right_arm",armor:40,power:24,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1873 43 -590 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:27,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_lightcircuit\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.paralyze\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.paralyze.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"7\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"60\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.peppercat\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_lightcurcuit.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_lightcurcuit.model\"}"]},medabots_server:{id:"medabots_server:peppercat_lightcurcuit",gender:1b,move:"paralyze",part:"head",armor:60,power:44,uses:7,activated:0b,version:1}}}]}
execute positioned -1873 43 -590 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=peppercat] MedabotNr

# Aimflash
summon minecraft:skeleton -1890 44 -596 {CustomName:"{\"translate\":\"medabots_server:entity.aimflash\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/boxer/first_go/aimflash",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["aimflash","enemy_medabot","killerable","hostile","wheel_legs","gatling_left_arm","laser_right_arm","falling_head","monkey_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] Stage 79
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] Medabot 26
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] Battle 1
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] MaxHeadUses 8
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] MaxHeadArmor 65
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] MaxRightArmArmor 20
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] MaxLeftArmArmor 45
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] MaxLegsArmor 50
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] HeadPower 20
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] RightArmPower 27
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] LeftArmPower 20
scoreboard players set @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] LegsDefense 28
scoreboard players operation @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] MedabotNr 1
execute as @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1890,y=44,z=-596,distance=..1,tag=aimflash] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1890 44 -596 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:26,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_carrybag\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.wheel\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.weel.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"50\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.aimflash\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_carrybag.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_carrybag.model\"}"]},medabots_server:{id:"medabots_server:aimflash_carrybag",gender:0b,move:"wheel",part:"legs",armor:50,defense:28,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1890 44 -596 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:26,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_tripod\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.gatling\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.gatling.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"45\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.aimflash\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_tripod.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_tripod.model\"}"]},medabots_server:{id:"medabots_server:aimflash_tripod",gender:0b,move:"gatling",part:"left_arm",armor:45,power:20,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1890 44 -596 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:26,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_zoom\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.laser\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.laser.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"20\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.aimflash\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_zoom.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_zoom.model\"}"]},medabots_server:{id:"medabots_server:aimflash_zoom",gender:0b,move:"laser",part:"right_arm",armor:20,power:27,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1890 44 -596 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:26,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_strobe\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.falling\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.falling.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"8\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"65\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.aimflash\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_strobe.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.aimflash_strobe.model\"}"]},medabots_server:{id:"medabots_server:aimflash_strobe",gender:0b,move:"falling",part:"head",armor:65,power:20,uses:8,activated:0b,version:1}}}]}
execute positioned -1890 44 -596 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=aimflash] MedabotNr

# Sailor-Multi
summon minecraft:skeleton -1908 44 -588 {CustomName:"{\"translate\":\"medabots_server:entity.sailor_multi\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/boxer/first_go/sailor_multi",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["sailor_multi","enemy_medabot","killerable","hostile","two_legged_legs","rifle_left_arm","gatling_right_arm","scout_head","spider_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] Stage 79
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] Medabot 39
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] Battle 1
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] MaxHeadUses 7
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] MaxHeadArmor 75
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] MaxRightArmArmor 35
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] MaxLeftArmArmor 35
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] MaxLegsArmor 40
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] HeadPower 50
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] RightArmPower 20
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] LeftArmPower 24
scoreboard players set @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] LegsDefense 40
scoreboard players operation @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] MedabotNr 1
execute as @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1908,y=44,z=-588,distance=..1,tag=sailor_multi] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1908 44 -588 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:39,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_flaregather\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.sailor_multi\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_flaregather.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_flaregather.model\"}"]},medabots_server:{id:"medabots_server:sailor_multi_flaregather",gender:1b,move:"two_legged",part:"legs",armor:40,defense:40,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1908 44 -588 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:39,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_short_shot\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.sailor_multi\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_short_shot.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_short_shot.model\"}"]},medabots_server:{id:"medabots_server:sailor_multi_short_shot",gender:1b,move:"rifle",part:"left_arm",armor:35,power:24,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1908 44 -588 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:39,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_pateri_vulcan\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.gatling\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.gatling.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.sailor_multi\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_pateri_vulcan.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_pateri_vulcan.model\"}"]},medabots_server:{id:"medabots_server:sailor_multi_pateri_vulcan",gender:1b,move:"gatling",part:"right_arm",armor:35,power:20,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1908 44 -588 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:39,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_variablehair\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.scout\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.scout.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"7\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"75\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.sailor_multi\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_variablehair.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.sailor_multi_variablehair.model\"}"]},medabots_server:{id:"medabots_server:sailor_multi_variablehair",gender:1b,move:"scout",part:"head",armor:75,power:50,uses:7,activated:0b,version:1}}}]}
execute positioned -1908 44 -588 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=sailor_multi] MedabotNr

# Dorcus
summon minecraft:skeleton -1917 44 -572 {CustomName:"{\"translate\":\"medabots_server:entity.dorcus\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/boxer/first_go/dorcus",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["dorcus","enemy_medabot","killerable","hostile","two_legged_legs","hammer_left_arm","sword_right_arm","scout_head","kuwagata_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] Stage 79
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] Medabot 32
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] Battle 1
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxHeadUses 6
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxHeadArmor 85
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxRightArmArmor 45
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxLeftArmArmor 45
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxLegsArmor 50
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] HeadPower 72
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] RightArmPower 32
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] LeftArmPower 52
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] LegsDefense 52
scoreboard players operation @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MedabotNr 1
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1917 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:32,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_windfluke\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"50\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.dorcus\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_windfluke.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_windfluke.model\"}"]},medabots_server:{id:"medabots_server:dorcus_windfluke",gender:0b,move:"two_legged",part:"legs",armor:50,defense:52,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1917 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:32,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_intensebeat\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.hammer\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.hammer.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"45\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.dorcus\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_intensebeat.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_intensebeat.model\"}"]},medabots_server:{id:"medabots_server:dorcus_intensebeat",gender:0b,move:"hammer",part:"left_arm",armor:45,power:52,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1917 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:32,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_fourvice\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.sword\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.sword.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"45\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.dorcus\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_fourvice.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_fourvice.model\"}"]},medabots_server:{id:"medabots_server:dorcus_fourvice",gender:0b,move:"sword",part:"right_arm",armor:45,power:32,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1917 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:32,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_twinincome\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.scout\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.scout.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"6\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"85\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.dorcus\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_twinincome.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.dorcus_twinincome.model\"}"]},medabots_server:{id:"medabots_server:dorcus_twinincome",gender:0b,move:"scout",part:"head",armor:85,power:72,uses:6,activated:0b,version:1}}}]}
execute positioned -1917 44 -572 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=dorcus] MedabotNr

# Potato-Insect
summon minecraft:skeleton -1906 43 -553 {CustomName:"{\"translate\":\"medabots_server:entity.potato_insect\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/boxer/first_go/potato_insect",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["potato_insect","enemy_medabot","killerable","hostile","wheel_legs","paralyze_left_arm","freeze_right_arm","bug_head","monkey_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] Stage 79
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] Medabot 0
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] Battle 1
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] MaxHeadUses 7
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] MaxHeadArmor 90
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] MaxRightArmArmor 25
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] MaxLeftArmArmor 40
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] MaxLegsArmor 55
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] HeadPower 25
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] RightArmPower 28
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] LeftArmPower 28
scoreboard players set @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] LegsDefense 28
scoreboard players operation @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] MedabotNr 1
execute as @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1906,y=43,z=-553,distance=..1,tag=potato_insect] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1906 43 -553 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:41,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.potato_insect_caterpie\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.wheel\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.weel.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"55\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.potato_insect\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.potato_insect_caterpie.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.potato_insect_caterpie.model\"}"]},medabots_server:{id:"medabots_server:potato_insect_caterpie",gender:1b,move:"wheel",part:"legs",armor:55,defense:28,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1906 43 -553 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:27,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_light_blow\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.paralyze\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.paralyze.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.peppercat\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_light_blow.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.peppercat_light_blow.model\"}"]},medabots_server:{id:"medabots_server:peppercat_light_blow",gender:1b,move:"paralyze",part:"left_arm",armor:40,power:28,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1906 43 -553 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:68,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.frappe_flap\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.freeze\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.freeze.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.frappe\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.frappe_flap.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.frappe_flap.model\"}"]},medabots_server:{id:"medabots_server:frappe_flap",gender:1b,move:"freeze",part:"right_arm",armor:35,power:26,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1906 43 -553 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:41,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.potato_insect_changedress\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.bug\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.bug.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"7\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"90\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.potato_insect\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.potato_insect_changedress.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.potato_insect_changedress.model\"}"]},medabots_server:{id:"medabots_server:potato_insect_changedress",gender:1b,move:"bug",part:"head",armor:90,power:25,uses:7,activated:0b,version:1}}}]}
execute positioned -1906 43 -553 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=potato_insect] MedabotNr

# Blackbeetle
summon minecraft:skeleton -1889 44 -574 {CustomName:"{\"translate\":\"medabots_server:entity.blackbeetle\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/battle_enemies/blackbeetle",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["blackbeetle","enemy_medabot","killerable","hostile","two_legged_legs","gating_left_arm","rifle_right_arm","missile_head","kabuto_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] Stage 79
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] Medabot 24
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] Battle 1
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] MaxHeadUses 6
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] MaxHeadArmor 65
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] MaxRightArmArmor 35
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] MaxLeftArmArmor 35
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] MaxLegsArmor 40
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] HeadPower 31
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] RightArmPower 40
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] LeftArmPower 28
scoreboard players set @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] LegsDefense 44
scoreboard players operation @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] MedabotNr 1
execute as @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1889,y=44,z=-574,distance=..1,tag=blackbeetle] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1889 44 -574 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:24,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackplace\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.two_legged.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.blackbeetle\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackplace.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackplace.model\"}"]},medabots_server:{id:"medabots_server:blackbeetle_blackplace",gender:1b,move:"two_legged",part:"legs",armor:40,defense:44,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1889 44 -574 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:24,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackblaster\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.gatling\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.gatling.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.blackbeetle\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackblaster.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackblaster.model\"}"]},medabots_server:{id:"medabots_server:blackbeetle_blackblaster",gender:1b,move:"gatling",part:"left_arm",armor:35,power:28,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1889 44 -574 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:24,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackfuser\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.rifle.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.blackbeetle\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackfuser.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackfuser.model\"}"]},medabots_server:{id:"medabots_server:blackbeetle_blackfuser",gender:1b,move:"rifle",part:"right_arm",armor:35,power:40,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1889 44 -574 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:24,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackbalister\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.missile\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.missile.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"6\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"65\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.blackbeetle\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackbalister.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.blackbeetle_blackbalister.model\"}"]},medabots_server:{id:"medabots_server:blackbeetle_blackbalister",gender:1b,move:"missile",part:"head",armor:65,power:31,uses:6,activated:0b,version:1}}}]}
execute positioned -1889 44 -574 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=blackbeetle] MedabotNr

# Player
teleport @s -1890 44 -548
function medabots_server:stage/create/boxer/first_go