execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=east,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/east/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=east,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/east/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=east,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/east/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=east,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/east/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=east,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/east/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=east,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/east/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=east,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/east/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=east,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/east/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=north,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/north/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=north,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/north/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=north,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/north/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=north,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/north/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=north,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/north/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=north,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/north/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=north,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/north/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=north,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/north/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=south,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/south/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=south,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/south/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=south,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/south/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=south,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/south/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=south,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/south/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=south,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/south/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=south,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/south/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=south,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/south/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=west,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/west/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=west,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/west/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=west,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/west/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=west,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/west/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=west,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/west/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=west,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/west/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=west,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/west/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=rotating,tag=west,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/rotating/west/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=east,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/east/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=east,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/east/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=east,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/east/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=east,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/east/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=east,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/east/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=east,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/east/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=east,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/east/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=east,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/east/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=north,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/north/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=north,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/north/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=north,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/north/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=north,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/north/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=north,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/north/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=north,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/north/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=north,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/north/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=north,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/north/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=south,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/south/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=south,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/south/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=south,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/south/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=south,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/south/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=south,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/south/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=south,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/south/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=south,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/south/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=south,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/south/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=west,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/west/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=west,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/west/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=west,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/west/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=west,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/west/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=west,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/west/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=west,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/west/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=west,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/west/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=detect,tag=looking,tag=west,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/detect/looking/west/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=east,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/east/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=east,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/east/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=east,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/east/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=east,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/east/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=east,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/east/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=east,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/east/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=east,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/east/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=east,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/east/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=north,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/north/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=north,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/north/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=north,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/north/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=north,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/north/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=north,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/north/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=north,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/north/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=north,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/north/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=north,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/north/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=south,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/south/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=south,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/south/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=south,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/south/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=south,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/south/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=south,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/south/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=south,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/south/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=south,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/south/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=south,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/south/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=west,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/west/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=west,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/west/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=west,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/west/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=west,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/west/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=west,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/west/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=west,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/west/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=west,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/west/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=rotating,tag=west,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/rotating/west/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=east,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/east/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=east,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/east/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=east,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/east/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=east,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/east/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=east,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/east/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=east,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/east/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=east,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/east/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=east,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/east/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=north,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/north/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=north,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/north/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=north,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/north/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=north,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/north/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=north,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/north/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=north,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/north/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=north,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/north/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=north,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/north/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=south,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/south/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=south,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/south/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=south,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/south/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=south,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/south/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=south,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/south/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=south,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/south/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=south,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/south/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=south,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/south/delay_8
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=west,tag=delay_1] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/west/delay_1
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=west,tag=delay_2] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/west/delay_2
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=west,tag=delay_3] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/west/delay_3
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=west,tag=delay_4] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/west/delay_4
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=west,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/west/delay_5
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=west,tag=delay_6] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/west/delay_6
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=west,tag=delay_7] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/west/delay_7
execute if entity @s[tag=cannon,tag=!enabled,tag=!detect,tag=looking,tag=west,tag=delay_8] run function medabots_server:set_blocks/action_floor/disabled/cannon/no_detect/looking/west/delay_8
execute if entity @s[tag=bomb,tag=!enabled,tag=delay_0] run function medabots_server:set_blocks/action_floor/disabled/bomb/delay_0
execute if entity @s[tag=bomb,tag=!enabled,tag=delay_5] run function medabots_server:set_blocks/action_floor/disabled/bomb/delay_5
execute if entity @s[tag=bomb,tag=!enabled,tag=delay_10] run function medabots_server:set_blocks/action_floor/disabled/bomb/delay_10
execute if entity @s[tag=bomb,tag=!enabled,tag=delay_30] run function medabots_server:set_blocks/action_floor/disabled/bomb/delay_30
execute if entity @s[tag=bomb,tag=!enabled,tag=delay_60] run function medabots_server:set_blocks/action_floor/disabled/bomb/delay_60
execute if entity @s[tag=bomb,tag=!enabled,tag=delay_90] run function medabots_server:set_blocks/action_floor/disabled/bomb/delay_90
execute if entity @s[tag=bomb,tag=!enabled,tag=delay_120] run function medabots_server:set_blocks/action_floor/disabled/bomb/delay_120
execute if entity @s[tag=balloon_bomb,tag=!enabled] run function medabots_server:set_blocks/action_floor/disabled/balloon_bomb
execute if entity @s[tag=guard,tag=!enabled,tag=slow] run function medabots_server:set_blocks/action_floor/disabled/guard/slow
execute if entity @s[tag=guard,tag=!enabled,tag=!slow,tag=!fast] run function medabots_server:set_blocks/action_floor/disabled/guard/normal
execute if entity @s[tag=guard,tag=!enabled,tag=fast] run function medabots_server:set_blocks/action_floor/disabled/guard/fast

execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=east,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/east/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=east,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/east/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=east,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/east/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=east,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/east/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=east,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/east/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=east,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/east/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=east,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/east/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=east,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/east/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=north,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/north/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=north,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/north/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=north,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/north/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=north,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/north/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=north,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/north/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=north,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/north/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=north,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/north/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=north,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/north/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=south,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/south/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=south,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/south/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=south,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/south/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=south,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/south/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=south,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/south/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=south,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/south/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=south,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/south/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=south,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/south/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=west,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/west/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=west,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/west/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=west,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/west/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=west,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/west/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=west,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/west/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=west,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/west/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=west,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/west/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=rotating,tag=west,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/rotating/west/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=east,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/east/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=east,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/east/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=east,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/east/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=east,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/east/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=east,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/east/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=east,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/east/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=east,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/east/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=east,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/east/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=north,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/north/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=north,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/north/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=north,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/north/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=north,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/north/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=north,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/north/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=north,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/north/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=north,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/north/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=north,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/north/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=south,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/south/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=south,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/south/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=south,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/south/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=south,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/south/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=south,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/south/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=south,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/south/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=south,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/south/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=south,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/south/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=west,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/west/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=west,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/west/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=west,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/west/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=west,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/west/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=west,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/west/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=west,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/west/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=west,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/west/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=detect,tag=looking,tag=west,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/detect/looking/west/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=east,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/east/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=east,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/east/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=east,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/east/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=east,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/east/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=east,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/east/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=east,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/east/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=east,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/east/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=east,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/east/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=north,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/north/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=north,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/north/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=north,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/north/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=north,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/north/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=north,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/north/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=north,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/north/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=north,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/north/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=north,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/north/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=south,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/south/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=south,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/south/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=south,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/south/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=south,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/south/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=south,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/south/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=south,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/south/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=south,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/south/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=south,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/south/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=west,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/west/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=west,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/west/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=west,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/west/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=west,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/west/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=west,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/west/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=west,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/west/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=west,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/west/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=rotating,tag=west,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/rotating/west/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=east,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/east/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=east,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/east/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=east,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/east/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=east,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/east/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=east,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/east/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=east,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/east/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=east,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/east/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=east,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/east/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=north,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/north/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=north,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/north/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=north,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/north/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=north,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/north/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=north,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/north/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=north,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/north/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=north,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/north/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=north,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/north/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=south,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/south/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=south,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/south/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=south,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/south/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=south,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/south/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=south,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/south/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=south,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/south/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=south,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/south/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=south,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/south/delay_8
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=west,tag=delay_1] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/west/delay_1
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=west,tag=delay_2] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/west/delay_2
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=west,tag=delay_3] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/west/delay_3
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=west,tag=delay_4] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/west/delay_4
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=west,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/west/delay_5
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=west,tag=delay_6] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/west/delay_6
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=west,tag=delay_7] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/west/delay_7
execute if entity @s[tag=cannon,tag=enabled,tag=!detect,tag=looking,tag=west,tag=delay_8] run function medabots_server:set_blocks/action_floor/enabled/cannon/no_detect/looking/west/delay_8
execute if entity @s[tag=bomb,tag=enabled,tag=delay_0] run function medabots_server:set_blocks/action_floor/enabled/bomb/delay_0
execute if entity @s[tag=bomb,tag=enabled,tag=delay_5] run function medabots_server:set_blocks/action_floor/enabled/bomb/delay_5
execute if entity @s[tag=bomb,tag=enabled,tag=delay_10] run function medabots_server:set_blocks/action_floor/enabled/bomb/delay_10
execute if entity @s[tag=bomb,tag=enabled,tag=delay_30] run function medabots_server:set_blocks/action_floor/enabled/bomb/delay_30
execute if entity @s[tag=bomb,tag=enabled,tag=delay_60] run function medabots_server:set_blocks/action_floor/enabled/bomb/delay_60
execute if entity @s[tag=bomb,tag=enabled,tag=delay_90] run function medabots_server:set_blocks/action_floor/enabled/bomb/delay_90
execute if entity @s[tag=bomb,tag=enabled,tag=delay_120] run function medabots_server:set_blocks/action_floor/enabled/bomb/delay_120
execute if entity @s[tag=balloon_bomb,tag=enabled] run function medabots_server:set_blocks/action_floor/enabled/balloon_bomb
execute if entity @s[tag=guard,tag=enabled,tag=slow] run function medabots_server:set_blocks/action_floor/enabled/guard/slow
execute if entity @s[tag=guard,tag=enabled,tag=!slow,tag=!fast] run function medabots_server:set_blocks/action_floor/enabled/guard/normal
execute if entity @s[tag=guard,tag=enabled,tag=fast] run function medabots_server:set_blocks/action_floor/enabled/guard/fast
