execute if entity @s[tag=jammy] run function medabots_server:set_blocks/pot/jammy
execute if entity @s[tag=balloon_bomb] run function medabots_server:set_blocks/pot/balloon_bomb
execute if entity @s[tag=bomb,tag=delay_0] run function medabots_server:set_blocks/pot/bomb/delay_0
execute if entity @s[tag=bomb,tag=delay_5] run function medabots_server:set_blocks/pot/bomb/delay_5
execute if entity @s[tag=bomb,tag=delay_10] run function medabots_server:set_blocks/pot/bomb/delay_10
execute if entity @s[tag=bomb,tag=delay_30] run function medabots_server:set_blocks/pot/bomb/delay_30
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=east,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/east/delay_4
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=east,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/east/delay_3
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=east,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/east/delay_2
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=east,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/east/delay_1
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=west,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/west/delay_4
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=west,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/west/delay_3
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=west,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/west/delay_2
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=west,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/west/delay_1
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=south,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/south/delay_4
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=south,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/south/delay_3
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=south,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/south/delay_2
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=south,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/south/delay_1
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=north,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/north/delay_4
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=north,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/north/delay_3
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=north,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/north/delay_2
execute if entity @s[tag=cannon,tag=!detect,tag=looking,tag=north,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/no_detect/looking/north/delay_1
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=east,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/east/delay_4
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=east,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/east/delay_3
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=east,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/east/delay_2
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=east,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/east/delay_1
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=west,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/west/delay_4
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=west,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/west/delay_3
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=west,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/west/delay_2
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=west,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/west/delay_1
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=south,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/south/delay_4
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=south,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/south/delay_3
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=south,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/south/delay_2
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=south,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/south/delay_1
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=north,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/north/delay_4
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=north,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/north/delay_3
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=north,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/north/delay_2
execute if entity @s[tag=cannon,tag=!detect,tag=rotating,tag=north,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/no_detect/rotating/north/delay_1
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=east,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/detect/looking/east/delay_4
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=east,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/detect/looking/east/delay_3
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=east,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/detect/looking/east/delay_2
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=east,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/detect/looking/east/delay_1
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=west,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/detect/looking/west/delay_4
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=west,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/detect/looking/west/delay_3
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=west,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/detect/looking/west/delay_2
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=west,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/detect/looking/west/delay_1
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=south,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/detect/looking/south/delay_4
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=south,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/detect/looking/south/delay_3
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=south,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/detect/looking/south/delay_2
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=south,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/detect/looking/south/delay_1
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=north,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/detect/looking/north/delay_4
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=north,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/detect/looking/north/delay_3
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=north,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/detect/looking/north/delay_2
execute if entity @s[tag=cannon,tag=detect,tag=looking,tag=north,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/detect/looking/north/delay_1
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=east,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/detect/rotating/east/delay_4
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=east,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/detect/rotating/east/delay_3
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=east,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/detect/rotating/east/delay_2
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=east,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/detect/rotating/east/delay_1
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=west,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/detect/rotating/west/delay_4
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=west,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/detect/rotating/west/delay_3
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=west,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/detect/rotating/west/delay_2
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=west,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/detect/rotating/west/delay_1
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=south,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/detect/rotating/south/delay_4
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=south,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/detect/rotating/south/delay_3
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=south,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/detect/rotating/south/delay_2
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=south,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/detect/rotating/south/delay_1
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=north,tag=delay_4] run function medabots_server:set_blocks/pot/cannon/detect/rotating/north/delay_4
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=north,tag=delay_3] run function medabots_server:set_blocks/pot/cannon/detect/rotating/north/delay_3
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=north,tag=delay_2] run function medabots_server:set_blocks/pot/cannon/detect/rotating/north/delay_2
execute if entity @s[tag=cannon,tag=detect,tag=rotating,tag=north,tag=delay_1] run function medabots_server:set_blocks/pot/cannon/detect/rotating/north/delay_1
execute if entity @s[tag=guard,tag=slow] run function medabots_server:set_blocks/pot/guard/slow
execute if entity @s[tag=guard,tag=!slow,tag=!fast] run function medabots_server:set_blocks/pot/guard/normal
execute if entity @s[tag=guard,tag=fast] run function medabots_server:set_blocks/pot/guard/fast

execute if entity @s[tag=!balloon_bomb,tag=!bomb,tag=!cannon,tag=!guard] run function medabots_server:set_blocks/pot
