# Grade Kabuki
summon minecraft:skeleton -1746 45 -460 {CustomName:'{"translate":"medabots_server:entity.grade_kabuki"}',CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/snowfield_b/second_go/grade_kabuki",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["grade_kabuki","enemy_medabot","killerable","hostile","wheel_legs","press_left_arm","scout_right_arm","confuse_head","alien_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
execute if entity @s[tag=practice_battle] run data merge entity @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki,limit=1] {DeathLootTable:"medabots_server:entities/battle_enemies/practice_round"}
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] Stage 14
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] Medabot 0
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] Killer 0
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] Charge 0
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] Battle 2
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] MaxHeadUses 6
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] MaxHeadArmor 75
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] MaxRightArmArmor 65
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] MaxLeftArmArmor 70
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] MaxLegsArmor 90
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] HeadPower 20
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] RightArmPower 31
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] LeftArmPower 24
scoreboard players set @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] LegsDefense 32
scoreboard players operation @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] MedabotNr 1
execute as @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1746,y=45,z=-460,distance=..1,tag=grade_kabuki] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1746 45 -460 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:4,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.grade_kabuki_flower_road"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.wheel"}','{"italic":false,"color":"white","translate":"medabots_server:move.wheel.description"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"90"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.grade_kabuki"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.grade_kabuki_flower_road.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.grade_kabuki_flower_road.model"}']},medabots_server:{stage_item:0b,id:"medabots_server:grade_kabuki_flower_road",gender:0b,move:"wheel",part:"legs",armor:90,defense:32,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1746 45 -460 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:31,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.dragonbeetle_veryweighter"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.press"}','{"italic":false,"color":"white","translate":"medabots_server:move.press.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.infinite"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"70"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.dragonbeetle"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.dragonbeetle_veryweighter.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.dragonbeetle_veryweighter.model"}']},medabots_server:{stage_item:0b,id:"medabots_server:dragonbeetle_veryweighter",gender:0b,move:"press",part:"left_arm",armor:70,power:24,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1746 45 -460 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:3,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.doctor_study_point_radar"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.scout"}','{"italic":false,"color":"white","translate":"medabots_server:move.scout.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.infinite"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"65"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.doctor_study"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.doctor_study_point_radar.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.doctor_study_point_radar.model"}']},medabots_server:{stage_item:0b,id:"medabots_server:doctor_study_point_radar",gender:0b,move:"scout",part:"right_arm",armor:65,power:31,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1746 45 -460 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:4,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.grade_kabuki_free_hair"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.confuse"}','{"italic":false,"color":"white","translate":"medabots_server:move.confuse.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.more","with":[{"text":"6"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"75"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.grade_kabuki"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.grade_kabuki_free_hair.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.grade_kabuki_free_hair.model"}']},medabots_server:{stage_item:0b,id:"medabots_server:grade_kabuki_free_hair",gender:0b,move:"confuse",part:"head",armor:75,power:20,uses:6,activated:0b,version:1}}}]}
execute positioned -1746 45 -460 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=grade_kabuki] MedabotNr