execute positioned ~-1 ~ ~ at @e[distance=..1,scores={Destroy=1..}] run scoreboard players add @s Moving 1
execute positioned ~ ~ ~-1 at @e[distance=..1,scores={Destroy=1..}] run scoreboard players add @s Moving 1
execute positioned ~1 ~ ~ at @e[distance=..1,scores={Destroy=1..}] run scoreboard players add @s Moving 1
execute positioned ~ ~ ~1 at @e[distance=..1,scores={Destroy=1..}] run scoreboard players add @s Moving 1
execute positioned ~-1 ~ ~ at @e[distance=..1,scores={Press=1..}] run scoreboard players add @s Moving 1
execute positioned ~ ~ ~-1 at @e[distance=..1,scores={Press=1..}] run scoreboard players add @s Moving 1
execute positioned ~1 ~ ~ at @e[distance=..1,scores={Press=1..}] run scoreboard players add @s Moving 1
execute positioned ~ ~ ~1 at @e[distance=..1,scores={Press=1..}] run scoreboard players add @s Moving 1
execute positioned ~-1 ~ ~ at @e[distance=..1,scores={Hammer=1..}] run scoreboard players add @s Moving 1
execute positioned ~ ~ ~-1 at @e[distance=..1,scores={Hammer=1..}] run scoreboard players add @s Moving 1
execute positioned ~1 ~ ~ at @e[distance=..1,scores={Hammer=1..}] run scoreboard players add @s Moving 1
execute positioned ~ ~ ~1 at @e[distance=..1,scores={Hammer=1..}] run scoreboard players add @s Moving 1