# Dorcus
summon minecraft:skeleton -1917 44 -572 {CustomName:'{"translate":"medabots_server:entity.dorcus"}',CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/boxer/first_go/dorcus",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["dorcus","enemy_medabot","killerable","hostile","two_legged_legs","hammer_left_arm","sword_right_arm","scout_head","kuwagata_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
execute if entity @s[tag=practice_battle] run data merge entity @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus,limit=1] {DeathLootTable:"medabots_server:entities/battle_enemies/practice_round"}
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] Stage 29
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] Medabot 32
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] Charge 0
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] Battle 2
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxHeadUses 6
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxHeadArmor 85
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxRightArmArmor 45
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxLeftArmArmor 45
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MaxLegsArmor 50
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] HeadPower 72
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] RightArmPower 32
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] LeftArmPower 52
scoreboard players set @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] LegsDefense 52
scoreboard players operation @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] MedabotNr 1
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1917,y=44,z=-572,distance=..1,tag=dorcus] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1917 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:32,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_windfluke"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.two_legged"}','{"italic":false,"color":"white","translate":"medabots_server:move.two_legged.description"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"50"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.dorcus"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_windfluke.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_windfluke.model"}']},medabots_server:{id:"medabots_server:dorcus_windfluke",gender:0b,move:"two_legged",part:"legs",armor:50,defense:52,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1917 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:32,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_intensebeat"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.hammer"}','{"italic":false,"color":"white","translate":"medabots_server:move.hammer.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.infinite"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"45"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.dorcus"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_intensebeat.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_intensebeat.model"}']},medabots_server:{id:"medabots_server:dorcus_intensebeat",gender:0b,move:"hammer",part:"left_arm",armor:45,power:52,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1917 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:32,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_fourvice"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.sword"}','{"italic":false,"color":"white","translate":"medabots_server:move.sword.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.infinite"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"45"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.dorcus"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_fourvice.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_fourvice.model"}']},medabots_server:{id:"medabots_server:dorcus_fourvice",gender:0b,move:"sword",part:"right_arm",armor:45,power:32,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1917 44 -572 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:32,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_twinincome"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.scout"}','{"italic":false,"color":"white","translate":"medabots_server:move.scout.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.more","with":[{"text":"6"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"85"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.dorcus"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_twinincome.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.dorcus_twinincome.model"}']},medabots_server:{id:"medabots_server:dorcus_twinincome",gender:0b,move:"scout",part:"head",armor:85,power:72,uses:6,activated:0b,version:1}}}]}
execute positioned -1917 44 -572 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=dorcus] MedabotNr