# Kasou Touchu
summon minecraft:skeleton -1611 45 -297 {CustomName:'{"translate":"medabots_server:entity.kasou_touchu"}',CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/ruins_out_a/first_go/kasou_touchu",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["kasou_touchu","enemy_medabot","killerable","hostile","wheel_legs","infect_left_arm","scout_right_arm","no_defend_head","alien_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
execute if entity @s[tag=practice_battle] run data merge entity @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu,limit=1] {DeathLootTable:"medabots_server:entities/battle_enemies/practice_round"}
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] Stage 7
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] Medabot 0
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] Charge 0
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] Battle 2
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] MaxHeadUses 8
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] MaxHeadArmor 80
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] MaxRightArmArmor 65
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] MaxLeftArmArmor 45
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] MaxLegsArmor 35
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] HeadPower 20
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] RightArmPower 31
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] LeftArmPower 38
scoreboard players set @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] LegsDefense 28
scoreboard players operation @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] MedabotNr 1
execute as @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1611,y=45,z=-297,distance=..1,tag=kasou_touchu] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1611 45 -297 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:5,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.kasou_touchu_fungoton"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.wheel"}','{"italic":false,"color":"white","translate":"medabots_server:move.wheel.description"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"35"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.kasou_touchu"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.kasou_touchu_fungoton.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.kasou_touchu_fungoton.model"}']},medabots_server:{id:"medabots_server:kasou_touchu_fungoton",gender:0b,move:"wheel",part:"legs",armor:35,defense:28,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1611 45 -297 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:6,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.maxsnake_jack"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.infect"}','{"italic":false,"color":"white","translate":"medabots_server:move.infect.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.infinite"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"45"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.maxsnake"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.maxsnake_jack.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.maxsnake_jack.model"}']},medabots_server:{id:"medabots_server:maxsnake_jack",gender:0b,move:"infect",part:"left_arm",armor:45,power:38,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1611 45 -297 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:3,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.doctor_study_point_radar"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.scout"}','{"italic":false,"color":"white","translate":"medabots_server:move.scout.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.infinite"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"65"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.doctor_study"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.doctor_study_point_radar.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.doctor_study_point_radar.model"}']},medabots_server:{id:"medabots_server:doctor_study_point_radar",gender:0b,move:"scout",part:"right_arm",armor:65,power:31,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1611 45 -297 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:5,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.kasou_touchu_mushroom"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.no_defend"}','{"italic":false,"color":"white","translate":"medabots_server:move.no_defend.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.more","with":[{"text":"8"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"80"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.kasou_touchu"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.kasou_touchu_mushroom.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.kasou_touchu_mushroom.model"}']},medabots_server:{id:"medabots_server:kasou_touchu_mushroom",gender:0b,move:"no_defend",part:"head",armor:80,power:20,uses:8,activated:0b,version:1}}}]}
execute positioned -1611 45 -297 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=kasou_touchu] MedabotNr