execute positioned -1594 45 -224 run function medabots_server:spawn_entities/guard/slow
execute positioned -1578 45 -222 run function medabots_server:spawn_entities/guard/slow
execute positioned -1592 45 -202 run function medabots_server:spawn_entities/guard/slow/2_medallar_cents
execute positioned -1603 45 -199 run function medabots_server:spawn_entities/guard/slow/2_medallar_cents
execute positioned -1613 45 -217 run function medabots_server:spawn_entities/guard/slow
execute positioned -1617 45 -225 run function medabots_server:spawn_entities/guard/slow
execute positioned -1624 45 -208 run function medabots_server:spawn_entities/guard/slow
execute positioned -1629 45 -211 run function medabots_server:spawn_entities/guard/slow
execute positioned -1634 45 -210 run function medabots_server:spawn_entities/guard/slow
execute positioned -1629 45 -202 run function medabots_server:spawn_entities/guard/slow
execute positioned -1627 45 -189 run function medabots_server:spawn_entities/guard/slow
execute positioned -1642 45 -214 run function medabots_server:spawn_entities/guard/slow
execute positioned -1650 45 -210 run function medabots_server:spawn_entities/guard/slow
execute positioned -1592 45 -230 run function medabots_server:spawn_entities/cannon/detect/rotating/west/delay_4
execute positioned -1600 45 -229 run function medabots_server:spawn_entities/cannon/detect/looking/east/delay_4
execute positioned -1577 45 -204 run function medabots_server:spawn_entities/cannon/detect/rotating/west/delay_4
execute positioned -1576 45 -198 run function medabots_server:spawn_entities/cannon/detect/rotating/west/delay_4
execute positioned -1604 45 -206 run function medabots_server:spawn_entities/cannon/detect/rotating/east/delay_4/2_medallar_cents
execute positioned -1659 45 -186 run function medabots_server:spawn_entities/cannon/detect/rotating/east/delay_4
execute positioned -1659 45 -187 run function medabots_server:spawn_entities/cannon/no_detect/rotating/east/delay_4
execute positioned -1607 45 -186 run function medabots_server:spawn_entities/cannon/detect/rotating/north/delay_4
execute positioned -1660 45 -214 run function medabots_server:spawn_entities/cannon/detect/rotating/south/delay_4
execute positioned -1643 45 -226 run function medabots_server:spawn_entities/cannon/detect/rotating/south/delay_4/4_medallar_cents
execute positioned -1647 45 -232 run function medabots_server:spawn_entities/cannon/detect/rotating/south/delay_4/4_medallar_cents
execute positioned -1628 45 -226 run function medabots_server:spawn_entities/cannon/detect/rotating/west/delay_4/4_medallar_cents
execute positioned -1636 45 -235 run function medabots_server:spawn_entities/cannon/detect/rotating/east/delay_4/4_medallar_cents
execute positioned -1616 45 -240 run function medabots_server:spawn_entities/cannon/detect/rotating/west/delay_4
execute positioned -1577 45 -207 run function medabots_server:spawn_entities/item/2_medallar_cents
execute positioned -1651 45.2 -215 run function medabots_server:spawn_entities/item/4_medallar_cents
execute positioned -1609 45 -231 run function medabots_server:spawn_entities/item/blue_plant
execute positioned -1610 45 -235 run function medabots_server:spawn_entities/item/4_medallar_cents
execute positioned -1581 45 -230 run function medabots_server:spawn_entities/ice_block
execute positioned -1578 45 -231 run function medabots_server:spawn_entities/ice_block
execute positioned -1579 45 -227 run function medabots_server:spawn_entities/ice_block
execute positioned -1578 45 -226 run function medabots_server:spawn_entities/ice_block
execute positioned -1580 45 -225 run function medabots_server:spawn_entities/ice_block
execute positioned -1626 45 -203 run function medabots_server:spawn_entities/ice_block
execute positioned -1628 45 -204 run function medabots_server:spawn_entities/ice_block
execute positioned -1631 45 -202 run function medabots_server:spawn_entities/ice_block
execute positioned -1630 45 -206 run function medabots_server:spawn_entities/ice_block
execute positioned -1624 45 -211 run function medabots_server:spawn_entities/ice_block
execute positioned -1628 45 -212 run function medabots_server:spawn_entities/ice_block
execute positioned -1632 45 -210 run function medabots_server:spawn_entities/ice_block
execute positioned -1634 45 -208 run function medabots_server:spawn_entities/ice_block
execute positioned -1657 45 -210 run function medabots_server:spawn_entities/ice_block
execute positioned -1655 45 -224 run function medabots_server:spawn_entities/ice_block
execute positioned -1657 45 -226 run function medabots_server:spawn_entities/ice_block
execute positioned -1659 45 -229 run function medabots_server:spawn_entities/ice_block
execute positioned -1657 45 -232 run function medabots_server:spawn_entities/ice_block
execute positioned -1654 45 -234 run function medabots_server:spawn_entities/ice_block
execute positioned -1663 45 -234 run function medabots_server:spawn_entities/ice_block
execute positioned -1657 45 -236 run function medabots_server:spawn_entities/ice_block
execute positioned -1654 45 -238 run function medabots_server:spawn_entities/ice_block
execute positioned -1661 45 -239 run function medabots_server:spawn_entities/ice_block
execute positioned -1658 45 -241 run function medabots_server:spawn_entities/ice_block
execute positioned -1651 45 -225 run function medabots_server:set_blocks/drawbridge/west
execute positioned -1632 45 -225 run function medabots_server:set_blocks/floor_switch/green
execute positioned -1627 45 -232 run function medabots_server:set_blocks/floor_switch/green
execute positioned -1643 45 -236 run function medabots_server:set_blocks/floor_switch/green
execute positioned -1649 45 -227 run function medabots_server:set_blocks/floor_switch/green
execute positioned -1594 45 -218 run function medabots_server:set_blocks/floor_switch/yellow/delay_5
execute positioned -1613 45 -203 run function medabots_server:set_blocks/floor_switch/blue
execute positioned -1617 45 -226 run function medabots_server:set_blocks/floor_switch/blue
execute positioned -1663 45 -187 run function medabots_server:set_blocks/floor_switch/blue
execute positioned -1663 45 -208 run function medabots_server:set_blocks/hole/delay_5
execute positioned -1660 45 -202 run function medabots_server:set_blocks/hole/delay_5
execute positioned -1663 45 -198 run function medabots_server:set_blocks/hole/delay_5
execute positioned -1592 45 -230 run function medabots_server:spawn_entities/raft
execute positioned -1600 45 -229 run function medabots_server:spawn_entities/raft
execute positioned -1594 45 -197 run function medabots_server:spawn_entities/raft
execute positioned -1616 45 -203 run function medabots_server:spawn_entities/raft
execute positioned -1617 45 -203 run function medabots_server:spawn_entities/raft
execute positioned -1618 45 -203 run function medabots_server:spawn_entities/raft
execute positioned -1619 45 -203 run function medabots_server:spawn_entities/raft
execute positioned -1627 45 -237 run function medabots_server:spawn_entities/raft
execute positioned -1627 45 -238 run function medabots_server:spawn_entities/raft
execute positioned -1627 45 -239 run function medabots_server:spawn_entities/raft
execute positioned -1632 45 -244 run function medabots_server:spawn_entities/raft
execute positioned -1633 45 -244 run function medabots_server:spawn_entities/raft
execute positioned -1622 45 -245 run function medabots_server:spawn_entities/raft
execute positioned -1621 45 -243 run function medabots_server:spawn_entities/raft
execute positioned -1620 45 -243 run function medabots_server:spawn_entities/raft
execute positioned -1619 45 -243 run function medabots_server:spawn_entities/raft
execute positioned -1618 45 -243 run function medabots_server:spawn_entities/raft
execute positioned -1616 45 -236 run function medabots_server:spawn_entities/raft
execute positioned -1617 45 -235 run function medabots_server:spawn_entities/raft
execute positioned -1616 45 -234 run function medabots_server:spawn_entities/raft
execute positioned -1615 45 -233 run function medabots_server:spawn_entities/raft
execute positioned -1614 45 -232 run function medabots_server:spawn_entities/raft
execute positioned -1613 45 -231 run function medabots_server:spawn_entities/raft
execute positioned -1612 45 -203 run function medabots_server:set_blocks/fan/off/west/range_8
execute positioned -1618 45 -226 run function medabots_server:set_blocks/laser_trap/disabled/west/delay_10
execute positioned -1655 45 -223 run function medabots_server:set_blocks/laser_trap/disabled/north/delay_10
execute positioned -1657 45 -225 run function medabots_server:set_blocks/laser_trap/disabled/north/delay_10
execute positioned -1659 45 -228 run function medabots_server:set_blocks/laser_trap/disabled/north/delay_10
execute positioned -1654 45 -239 run function medabots_server:set_blocks/laser_trap/disabled/south/delay_10
execute positioned -1661 45 -240 run function medabots_server:set_blocks/laser_trap/disabled/south/delay_10
execute positioned -1658 45 -242 run function medabots_server:set_blocks/laser_trap/disabled/south/delay_10
execute positioned -1610 45 -232 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1608 45 -230 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1657 45 -211 run function medabots_server:set_blocks/spring_wall/disabled/south/delay_10
execute positioned -1653 45 -230 run function medabots_server:spawn_entities/item/rubberobo_help
execute positioned -1653 45 -230 run function medabots_server:spawn_entities/rubberobo/south
execute positioned -1592 45 -244 run function medabots_server:set_blocks/pot/2_medallar_cents
execute positioned -1588 45 -243 run function medabots_server:set_blocks/pot
execute positioned -1587 45 -241 run function medabots_server:set_blocks/pot
execute positioned -1596 45 -242 run function medabots_server:set_blocks/pot
execute positioned -1594 45 -240 run function medabots_server:set_blocks/pot
execute positioned -1598 45 -240 run function medabots_server:set_blocks/pot/2_medallar_cents
execute positioned -1596 45 -235 run function medabots_server:set_blocks/pot
execute positioned -1579 45 -235 run function medabots_server:set_blocks/pot/guard/slow
execute positioned -1577 45 -234 run function medabots_server:set_blocks/pot/guard/slow
execute positioned -1577 45 -236 run function medabots_server:set_blocks/pot
execute positioned -1575 45 -238 run function medabots_server:set_blocks/pot/6_medallar_cents
# Medapa pot
execute positioned -1576 45 -201 run function medabots_server:set_blocks/pot
replaceitem block -1576 45 -201 container.0 minecraft:fishing_rod{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:22,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.abyss_greater_pro_fence"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.sacrifice"}','{"italic":false,"color":"white","translate":"medabots_server:move.sacrifice.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.1"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"50"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.abyss_greater"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.abyss_greater_pro_fence.model"}']},medabots_server:{stage_item:1b,id:"medabots_server:abyss_greater_pro_fence",gender:0b,move:"sacrifice",part:"left_arm",armor:50,power:54,activated:0b,version:1}}
execute positioned -1610 45 -211 run function medabots_server:set_blocks/pot/bomb/delay_5
execute positioned -1615 45 -209 run function medabots_server:set_blocks/pot/bomb/delay_5
execute positioned -1610 45 -214 run function medabots_server:set_blocks/pot/4_medallar_cents
execute positioned -1618 45 -216 run function medabots_server:set_blocks/pot/bomb/delay_5
execute positioned -1620 45 -220 run function medabots_server:set_blocks/pot/bomb/delay_5
execute positioned -1613 45 -223 run function medabots_server:set_blocks/pot/guard/slow
execute positioned -1644 45 -186 run function medabots_server:set_blocks/pot/bomb/delay_5
execute positioned -1630 45 -192 run function medabots_server:set_blocks/pot
execute positioned -1626 45 -193 run function medabots_server:set_blocks/pot
execute positioned -1623 45 -190 run function medabots_server:set_blocks/pot
execute positioned -1611 45 -187 run function medabots_server:set_blocks/pot
execute positioned -1607 45 -188 run function medabots_server:set_blocks/pot/4_medallar_cents
execute positioned -1603 45 -190 run function medabots_server:set_blocks/pot
execute positioned -1596 45 -190 run function medabots_server:set_blocks/pot/guard/slow/4_medallar_cents
execute positioned -1594 45 -193 run function medabots_server:set_blocks/pot/balloon_bomb
execute positioned -1593 45 -189 run function medabots_server:set_blocks/pot/4_medallar_cents
execute positioned -1592 45 -191 run function medabots_server:set_blocks/pot/bomb/delay_5
execute positioned -1589 45 -191 run function medabots_server:set_blocks/pot
execute positioned -1590 45 -189 run function medabots_server:set_blocks/pot/cannon/detect/rotating/north/delay_4
execute positioned -1666 45 -210 run function medabots_server:set_blocks/pot/6_medallar_cents
execute positioned -1664 45 -198 run function medabots_server:set_blocks/pot/guard/slow/10_medallar_cents
execute positioned -1629 45 -243 run function medabots_server:set_blocks/pot
execute positioned -1629 45 -244 run function medabots_server:set_blocks/pot
execute positioned -1623 45 -242 run function medabots_server:set_blocks/pot
execute positioned -1623 45 -243 run function medabots_server:set_blocks/pot
execute positioned -1606 45 -245 run function medabots_server:set_blocks/pot
execute positioned -1605 45 -242 run function medabots_server:set_blocks/pot
execute positioned -1603 45 -241 run function medabots_server:set_blocks/pot
execute positioned -1603 45 -244 run function medabots_server:set_blocks/pot/6_medallar_cents
execute positioned -1607 45 -206 run function medabots_server:set_blocks/bridge
execute positioned -1608 45 -206 run function medabots_server:set_blocks/bridge
execute positioned -1616 45 -204 run function medabots_server:set_blocks/bridge
execute positioned -1617 45 -204 run function medabots_server:set_blocks/bridge
execute positioned -1618 45 -204 run function medabots_server:set_blocks/bridge
execute positioned -1619 45 -204 run function medabots_server:set_blocks/bridge
execute positioned -1622 45 -204 run function medabots_server:set_blocks/bridge
execute positioned -1622 45 -203 run function medabots_server:set_blocks/bridge
execute positioned -1598 45 -217 run function medabots_server:set_blocks/accelerator/south
execute positioned -1590 45 -213 run function medabots_server:set_blocks/accelerator/south
execute positioned -1598 45 -207 run function medabots_server:set_blocks/accelerator/south
execute positioned -1642 45 -207 run function medabots_server:set_blocks/accelerator/south
execute positioned -1651 45 -215 run function medabots_server:set_blocks/accelerator/south
execute positioned -1647 45 -209 run function medabots_server:set_blocks/accelerator/west
execute positioned -1599 45 -188 run function medabots_server:set_blocks/accelerator/north
execute positioned -1599 45 -189 run function medabots_server:set_blocks/accelerator/north
execute positioned -1599 45 -190 run function medabots_server:set_blocks/accelerator/north
execute positioned -1599 45 -191 run function medabots_server:set_blocks/accelerator/north
execute positioned -1652 45 -206 run function medabots_server:set_blocks/accelerator/east
execute positioned -1655 45 -210 run function medabots_server:set_blocks/accelerator/east
execute positioned -1652 45 -228 run function medabots_server:set_blocks/wall
execute positioned -1652 45 -231 run function medabots_server:set_blocks/wall
execute positioned -1598 45 -213 run function medabots_server:set_blocks/door/closed/north
execute positioned -1590 45 -207 run function medabots_server:set_blocks/door/closed/north
execute positioned -1652 45 -229 run function medabots_server:set_blocks/door/closed/east
execute positioned -1660 45 -234 run function medabots_server:set_blocks/goal_area
execute positioned -1594 45 -243 run function medabots_server:set_blocks/starting_area
tag @s add rubberobo
teleport @s -1594 45 -243
bossbar set medabots_server:snowfield_a/time value 0
bossbar set medabots_server:snowfield_a/time players @s
scoreboard players set @a[x=-1668,y=43,z=-247,dx=105,dy=7,dz=63] Battle 1
scoreboard players set @a[x=-1668,y=43,z=-247,dx=105,dy=7,dz=63] Stage 5
scoreboard players set @a[x=-1668,y=43,z=-247,dx=105,dy=7,dz=63] Music 0
scoreboard players set @a[x=-1668,y=43,z=-247,dx=105,dy=7,dz=63] MusicType 11