tag @s add success
execute if entity @s[advancements={medabots_server:wave_1/get_all_medabots/crimson_king={legs=false,left_arm=false,right_arm=false,head=false}}] run tag @s add out_of_stock
tellraw @s[tag=out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.not_available"}]}
tellraw @s[tag=!out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.medapart"}]}
tag @s remove out_of_stock
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/crimson_king={legs=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 65"},"with":[{"translate":"medabots_server:entity.crimson_king","extra":[{"text":" "},{"translate":"medabots_server:item.crimson_king_wannafly"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/crimson_king={left_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 66"},"with":[{"translate":"medabots_server:entity.crimson_king","extra":[{"text":" "},{"translate":"medabots_server:item.crimson_king_dopa_punch"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/crimson_king={right_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 67"},"with":[{"translate":"medabots_server:entity.crimson_king","extra":[{"text":" "},{"translate":"medabots_server:item.crimson_king_dondon_punch"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/crimson_king={head=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 68"},"with":[{"translate":"medabots_server:entity.crimson_king","extra":[{"text":" "},{"translate":"medabots_server:item.crimson_king_peck_strike"}]},{"text":"100"}]}
tag @s add final