tag @s add success
execute if entity @s[advancements={medabots_server:wave_1/get_all_medabots/aimflash={legs=false,left_arm=false,right_arm=false,head=false}}] run tag @s add out_of_stock
tellraw @s[tag=out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.not_available"}]}
tellraw @s[tag=!out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.medapart"}]}
tag @s remove out_of_stock
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/aimflash={legs=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 21"},"with":[{"translate":"medabots_server:entity.aimflash","extra":[{"text":" "},{"translate":"medabots_server:item.aimflash_carrybag"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/aimflash={left_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 22"},"with":[{"translate":"medabots_server:entity.aimflash","extra":[{"text":" "},{"translate":"medabots_server:item.aimflash_tripod"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/aimflash={right_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 23"},"with":[{"translate":"medabots_server:entity.aimflash","extra":[{"text":" "},{"translate":"medabots_server:item.aimflash_zoom"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/aimflash={head=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 24"},"with":[{"translate":"medabots_server:entity.aimflash","extra":[{"text":" "},{"translate":"medabots_server:item.aimflash_strobe"}]},{"text":"100"}]}
tag @s add final