tag @s add success
execute if entity @s[advancements={medabots_server:wave_1/get_all_medabots/bezelga={legs=false,left_arm=false,right_arm=false,head=false}}] run tag @s add out_of_stock
tellraw @s[tag=out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.not_available"}]}
tellraw @s[tag=!out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.medapart"}]}
tag @s remove out_of_stock
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/bezelga={legs=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 49"},"with":[{"translate":"medabots_server:entity.bezelga","extra":[{"text":" "},{"translate":"medabots_server:item.bezelga_helcaos"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/bezelga={left_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 50"},"with":[{"translate":"medabots_server:entity.bezelga","extra":[{"text":" "},{"translate":"medabots_server:item.bezelga_helming"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/bezelga={right_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 51"},"with":[{"translate":"medabots_server:entity.bezelga","extra":[{"text":" "},{"translate":"medabots_server:item.bezelga_helmight"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/bezelga={head=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 52"},"with":[{"translate":"medabots_server:entity.bezelga","extra":[{"text":" "},{"translate":"medabots_server:item.bezelga_helmet"}]},{"text":"100"}]}
