tag @s add success
execute if entity @s[advancements={medabots_server:wave_1/get_all_medabots/ashton={legs=false,left_arm=false,right_arm=false,head=false}}] run tag @s add out_of_stock
tellraw @s[tag=out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.not_available"}]}
tellraw @s[tag=!out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.medapart"}]}
tag @s remove out_of_stock
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/ashton={legs=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 33"},"with":[{"translate":"medabots_server:entity.ashton","extra":[{"text":" "},{"translate":"medabots_server:item.ashton_ash_leg"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/ashton={left_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 34"},"with":[{"translate":"medabots_server:entity.ashton","extra":[{"text":" "},{"translate":"medabots_server:item.ashton_ash_buster"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/ashton={right_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 35"},"with":[{"translate":"medabots_server:entity.ashton","extra":[{"text":" "},{"translate":"medabots_server:item.ashton_ash_breaker"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/ashton={head=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 36"},"with":[{"translate":"medabots_server:entity.ashton","extra":[{"text":" "},{"translate":"medabots_server:item.ashton_booster_head"}]},{"text":"100"}]}
tag @s add final