tag @s add success
execute if entity @s[advancements={medabots_server:wave_1/get_all_medabots/pure_mermaid={legs=false,left_arm=false,right_arm=false,head=false}}] run tag @s add out_of_stock
tellraw @s[tag=out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.not_available"}]}
tellraw @s[tag=!out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.medapart"}]}
tag @s remove out_of_stock
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/pure_mermaid={legs=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 209"},"with":[{"translate":"medabots_server:entity.pure_mermaid","extra":[{"text":" "},{"translate":"medabots_server:item.pure_mermaid_purple_fins"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/pure_mermaid={left_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 210"},"with":[{"translate":"medabots_server:entity.pure_mermaid","extra":[{"text":" "},{"translate":"medabots_server:item.pure_mermaid_repair_arm"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/pure_mermaid={right_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 211"},"with":[{"translate":"medabots_server:entity.pure_mermaid","extra":[{"text":" "},{"translate":"medabots_server:item.pure_mermaid_cure_hand"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/pure_mermaid={head=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 212"},"with":[{"translate":"medabots_server:entity.pure_mermaid","extra":[{"text":" "},{"translate":"medabots_server:item.pure_mermaid_allrepair"}]},{"text":"100"}]}
