tag @s add success
execute if entity @s[advancements={medabots_server:wave_1/get_all_medabots/pinguen={legs=false,left_arm=false,right_arm=false,head=false}}] run tag @s add out_of_stock
tellraw @s[tag=out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.not_available"}]}
tellraw @s[tag=!out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.medapart"}]}
tag @s remove out_of_stock
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/pinguen={legs=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 189"},"with":[{"translate":"medabots_server:entity.pinguen","extra":[{"text":" "},{"translate":"medabots_server:item.pinguen_fin"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/pinguen={left_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 190"},"with":[{"translate":"medabots_server:entity.pinguen","extra":[{"text":" "},{"translate":"medabots_server:item.pinguen_new_arm"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/pinguen={right_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 191"},"with":[{"translate":"medabots_server:entity.pinguen","extra":[{"text":" "},{"translate":"medabots_server:item.pinguen_free_arm"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/pinguen={head=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 192"},"with":[{"translate":"medabots_server:entity.pinguen","extra":[{"text":" "},{"translate":"medabots_server:item.pinguen_zera_reactor"}]},{"text":"100"}]}
tag @s add final