tag @s add success
execute if entity @s[advancements={medabots_server:wave_1/get_all_medabots/maxsnake={legs=false,left_arm=false,right_arm=false,head=false}}] run tag @s add out_of_stock
tellraw @s[tag=out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.not_available"}]}
tellraw @s[tag=!out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.medapart"}]}
tag @s remove out_of_stock
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/maxsnake={legs=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 165"},"with":[{"translate":"medabots_server:entity.maxsnake","extra":[{"text":" "},{"translate":"medabots_server:item.maxsnake_musk"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/maxsnake={left_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 166"},"with":[{"translate":"medabots_server:entity.maxsnake","extra":[{"text":" "},{"translate":"medabots_server:item.maxsnake_jack"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/maxsnake={right_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 167"},"with":[{"translate":"medabots_server:entity.maxsnake","extra":[{"text":" "},{"translate":"medabots_server:item.maxsnake_virus"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/maxsnake={head=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 168"},"with":[{"translate":"medabots_server:entity.maxsnake","extra":[{"text":" "},{"translate":"medabots_server:item.maxsnake_hacker"}]},{"text":"100"}]}
