tag @s add success
execute if entity @s[advancements={medabots_server:wave_1/get_all_medabots/acehorn={legs=false,left_arm=false,right_arm=false,head=false}}] run tag @s add out_of_stock
tellraw @s[tag=out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.not_available"}]}
tellraw @s[tag=!out_of_stock] {"translate":"chat.type.text","with":[{"translate":"medabots_server:entity.medabot_salesman"},{"translate":"medabots_server:message.shop.medapart"}]}
tag @s remove out_of_stock
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/acehorn={legs=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 17"},"with":[{"translate":"medabots_server:entity.acehorn","extra":[{"text":" "},{"translate":"medabots_server:item.acehorn_ace_hooves"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/acehorn={left_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 18"},"with":[{"translate":"medabots_server:entity.acehorn","extra":[{"text":" "},{"translate":"medabots_server:item.acehorn_recovery"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/acehorn={right_arm=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 19"},"with":[{"translate":"medabots_server:entity.acehorn","extra":[{"text":" "},{"translate":"medabots_server:item.acehorn_canceller"}]},{"text":"100"}]}
tellraw @s[advancements={medabots_server:wave_1/get_all_medabots/acehorn={head=true}}] {"translate":"medabots_server:message.shop.buy","clickEvent":{"action":"run_command","value":"/trigger BuyMedapart set 20"},"with":[{"translate":"medabots_server:entity.acehorn","extra":[{"text":" "},{"translate":"medabots_server:item.acehorn_guardian"}]},{"text":"100"}]}
