# Pure Mermaid
summon minecraft:skeleton -1538 45 -230 {CustomName:"{\"translate\":\"medabots_server:entity.pure_mermaid\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/seashore_a/first_go/pure_mermaid",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["pure_mermaid","enemy_medabot","killerable","hostile","swim_legs","shooting_trap_left_arm","feeze_right_arm","heal_head","mermaid_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] Stage 4
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] Medabot 0
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] Battle 2
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] MaxHeadUses 10
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] MaxHeadArmor 65
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] MaxRightArmArmor 35
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] MaxLeftArmArmor 45
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] MaxLegsArmor 50
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] HeadPower 10
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] RightArmPower 36
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] LeftArmPower 32
scoreboard players set @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] LegsDefense 64
scoreboard players operation @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] MedabotNr 1
execute as @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1538,y=45,z=-230,distance=..1,tag=pure_mermaid] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1538 45 -230 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:43,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pure_mermaid_purple_fins\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.swim\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.swim.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"50\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.pure_mermaid\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pure_mermaid_purple_fins.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pure_mermaid_purple_fins.model\"}"]},medabots_server:{id:"medabots_server:pure_mermaid_purple_fins",gender:1b,move:"swim",part:"legs",armor:50,defense:64,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1538 45 -230 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:37,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pastel_fairy_force_barrier\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.shooting_trap\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.shooting_trap.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"45\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.pastel_fairy\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pastel_fairy_force_barrier.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pastel_fairy_force_barrier.model\"}"]},medabots_server:{id:"medabots_server:pastel_fairy_force_barrier",gender:1b,move:"shooting_trap",part:"left_arm",armor:45,power:32,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1538 45 -230 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:68,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.frappe_flap\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.freeze\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.freeze.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.frappe\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.frappe_flap.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.frappe_flap.model\"}"]},medabots_server:{id:"medabots_server:frappe_flap",gender:1b,move:"freeze",part:"right_arm",armor:35,power:26,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1538 45 -230 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:43,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pure_mermaid_allrepair\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.heal\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.heal.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"10\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"65\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.pure_mermaid\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pure_mermaid_allrepair.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pure_mermaid_allrepair.model\"}"]},medabots_server:{id:"medabots_server:pure_mermaid_allrepair",gender:1b,move:"heal",part:"head",armor:65,power:10,uses:10,activated:0b,version:1}}}]}
execute positioned -1538 45 -230 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=pure_mermaid] MedabotNr