# Give weapon to user
execute unless entity @s[scores={ScoutTime=1..}] if entity @s[type=!minecraft:player] anchored eyes run summon minecraft:item ^ ^-0.2 ^ {Item:{id:"minecraft:purple_wool",Count:1b,tag:{CustomModelData:1,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:move.chameleon_medal"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.chameleon_medal"}','{"italic":false,"color":"white","translate":"medabots_server:item.generic.drop"}']},medabots_server:{id:"medabots_server:damage_ball",team:"enemy"}}},Tags:["damage_ball","new"],PickupDelay:32767s}
execute if entity @s[scores={ScoutTime=1..},type=!minecraft:player] anchored eyes run summon minecraft:item ^ ^-0.2 ^ {Item:{id:"minecraft:purple_wool",Count:1b,tag:{CustomModelData:1,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:move.chameleon_medal"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.chameleon_medal"}','{"italic":false,"color":"white","translate":"medabots_server:item.generic.drop"}']},medabots_server:{id:"medabots_server:damage_ball",team:"enemy",strong:1b}}},Tags:["damage_ball","new"],PickupDelay:32767s}
execute if entity @s[type=!minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^-0.2 ^2 {CustomName:'{"translate":"medabots_server:move.chameleon_medal"}',Tags:["damage_ball"],Duration:1}
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] store result score @s PosX run data get entity @s Pos[0] 100
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] store result score @s PosY run data get entity @s Pos[1] 100
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] store result score @s PosZ run data get entity @s Pos[2] 100
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] store result score @s OtherX run data get entity @e[type=minecraft:area_effect_cloud,tag=damage_ball,limit=1] Pos[0] 100
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] store result score @s OtherY run data get entity @e[type=minecraft:area_effect_cloud,tag=damage_ball,limit=1] Pos[1] 100
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] store result score @s OtherZ run data get entity @e[type=minecraft:area_effect_cloud,tag=damage_ball,limit=1] Pos[2] 100
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] run scoreboard players operation @s OtherX -= @s PosX
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] run scoreboard players operation @s OtherY -= @s PosY
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] run scoreboard players operation @s OtherZ -= @s PosZ
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] store result entity @s Motion[0] double 0.01 run scoreboard players get @s OtherX
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] store result entity @s Motion[1] double 0.01 run scoreboard players get @s OtherY
execute if entity @s[type=!minecraft:player] as @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] store result entity @s Motion[2] double 0.01 run scoreboard players get @s OtherZ
execute if entity @s[type=!minecraft:player] run tag @e[type=minecraft:item,tag=damage_ball,distance=..6,sort=nearest,limit=1,tag=new] remove new
execute if entity @s[type=!minecraft:player] run kill @e[type=minecraft:area_effect_cloud,tag=damage_ball]
