# Increase time by 1
scoreboard players add @s Time 1

# Set which part is activated
scoreboard players set @s[scores={Time=2,Break=1},nbt={Inventory:[{Slot:1b,tag:{medabots_server:{id:"medabots_server:boarbooster_wollybond"}}}]}] MedapartType 1
scoreboard players set @s[scores={Time=2,Break=3},nbt={Inventory:[{Slot:2b,tag:{medabots_server:{id:"medabots_server:boarbooster_drillril"}}}]}] MedapartType 2
scoreboard players set @s[scores={Time=2,Break=2},nbt={Inventory:[{Slot:3b,tag:{medabots_server:{id:"medabots_server:god_emperor_death_break"}}}]}] MedapartType 3
scoreboard players set @s[scores={Time=2,Break=3},nbt={Inventory:[{Slot:2b,tag:{medabots_server:{id:"medabots_server:king_pharaoh_black_hall"}}}]}] MedapartType 4
scoreboard players set @s[scores={Time=2,Break=3},nbt={Inventory:[{Slot:2b,tag:{medabots_server:{id:"medabots_server:uglyduck_feathermend"}}}]}] MedapartType 5
scoreboard players set @s[scores={Time=2,Break=1},nbt={Inventory:[{Slot:1b,tag:{medabots_server:{id:"medabots_server:rob_gyro_hand"}}}]}] MedapartType 6
scoreboard players set @s[scores={Time=2,Break=1},nbt={Inventory:[{Slot:1b,tag:{medabots_server:{id:"medabots_server:yuchitang_minus_diver"}}}]}] MedapartType 7
scoreboard players set @s[scores={Time=2,Break=2},nbt={Inventory:[{Slot:3b,tag:{medabots_server:{id:"medabots_server:yuchitang_power_diver"}}}]}] MedapartType 8
scoreboard players set @s[scores={Time=2,Break=3},nbt={Inventory:[{Slot:2b,tag:{medabots_server:{id:"medabots_server:yuchitang_plus_diver"}}}]}] MedapartType 9

# Jump the time value up for right and left arm
scoreboard players set @s[scores={Time=3,Break=1}] Time 19
scoreboard players set @s[scores={Time=3,Break=3}] Time 27

# Give the weapon
replaceitem entity @s[scores={Break=1,Time=32..34,Drop=0},tag=!ally_medabot,tag=!enemy_medabot] hotbar.1 minecraft:black_wool{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"none"}}
replaceitem entity @s[scores={Break=3,Time=32..34,Drop=0},tag=!ally_medabot,tag=!enemy_medabot] hotbar.2 minecraft:black_wool{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"none"}}
replaceitem entity @s[scores={Break=2,Time=32..34,Drop=0},tag=!ally_medabot,tag=!enemy_medabot] hotbar.3 minecraft:black_wool{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"none"}}
replaceitem entity @s[scores={Break=1,Time=32..34,Drop=0},tag=ally_medabot] hotbar.1 minecraft:black_wool{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"ally"}}
replaceitem entity @s[scores={Break=3,Time=32..34,Drop=0},tag=ally_medabot] hotbar.2 minecraft:black_wool{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"ally"}}
replaceitem entity @s[scores={Break=2,Time=32..34,Drop=0},tag=ally_medabot] hotbar.3 minecraft:black_wool{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"ally"}}
replaceitem entity @s[scores={Break=1,Time=32..34,Drop=0},tag=enemy_medabot] hotbar.1 minecraft:black_wool{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"enemy"}}
replaceitem entity @s[scores={Break=3,Time=32..34,Drop=0},tag=enemy_medabot] hotbar.2 minecraft:black_wool{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"enemy"}}
replaceitem entity @s[scores={Break=2,Time=32..34,Drop=0},tag=enemy_medabot] hotbar.3 minecraft:black_wool{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"enemy"}}
execute if entity @s[scores={Break=1..,Time=32},type=!minecraft:player] anchored eyes run summon minecraft:item ^ ^ ^2.5 {Item:{id:"minecraft:break_wool",Count:1b,tag:{display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.generic.drop\"}"]},medabots_server:{id:"medabots_server:break",team:"enemy"}}}}

# Remove from head uses if this was the head part
scoreboard players remove @s[scores={Break=2,Time=34}] HeadUses 1

# Remove the weapon
clear @s[scores={Time=90}] minecraft:black_wool{medabots_server:{id:"medabots_server:break"}}

# Give back the original part
replaceitem entity @s[scores={MedapartType=1,Time=92..,Drop=0}] hotbar.1 minecraft:fishing_rod{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:29,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.boarbooster_wollybond\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"50\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.boarbooster\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.boarbooster_wollybond.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.boarbooster_wollybond.model\"}"]},medabots_server:{id:"medabots_server:boarbooster_wollybond",gender:1b,move:"break",part:"left_arm",armor:50,power:36,activated:1b,version:1}}
replaceitem entity @s[scores={MedapartType=2,Time=92..,Drop=0}] hotbar.2 minecraft:fishing_rod{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:29,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.boarbooster_drillril\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"50\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.boarbooster\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.boarbooster_drillril.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.boarbooster_drillril.model\"}"]},medabots_server:{id:"medabots_server:boarbooster_drillril",gender:1b,move:"break",part:"right_arm",armor:50,power:30,activated:1b,version:1}}
replaceitem entity @s[scores={MedapartType=3,Time=92..,Drop=0}] hotbar.3 minecraft:fishing_rod{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:17,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.god_emperor_death_break\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"7\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"50\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.god_emperor\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.god_emperor_death_break.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.god_emperor_death_break.model\"}"]},medabots_server:{id:"medabots_server:god_emperor_death_break",gender:0b,move:"break",part:"head",armor:50,power:52,uses:7,activated:1b,version:1}}
replaceitem entity @s[scores={MedapartType=4,Time=92..,Drop=0}] hotbar.2 minecraft:fishing_rod{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:33,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.king_pharaoh_black_hall\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"80\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.king_pharaoh\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.king_pharaoh_black_hall.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.king_pharaoh_black_hall.model\"}"]},medabots_server:{id:"medabots_server:king_pharaoh_black_hall",gender:0b,move:"break",part:"right_arm",armor:80,power:18,activated:1b,version:1}}
replaceitem entity @s[scores={MedapartType=5,Time=92..,Drop=0}] hotbar.2 minecraft:fishing_rod{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:42,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.uglyduck_feathermend\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"65\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.uglyduck\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.uglyduck_feathermend.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.uglyduck_feathermend.model\"}"]},medabots_server:{id:"medabots_server:uglyduck_feathermend",gender:1b,move:"break",part:"right_arm",armor:65,power:26,activated:1b,version:1}}
replaceitem entity @s[scores={MedapartType=6,Time=92..,Drop=0}] hotbar.1 minecraft:fishing_rod{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:49,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.rob_gyro_hand\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.rob\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.rob_gyro_hand.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.rob_gyro_hand.model\"}"]},medabots_server:{id:"medabots_server:rob_gyro_hand",gender:0b,move:"break",part:"left_arm",armor:35,power:28,activated:1b,version:1}}
replaceitem entity @s[scores={MedapartType=7,Time=92..,Drop=0}] hotbar.1 minecraft:fishing_rod{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:59,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.yuchitang_minus_diver\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"10\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.yuchitang\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.yuchitang_minus_diver.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.yuchitang_minus_diver.model\"}"]},medabots_server:{id:"medabots_server:yuchitang_minus_diver",gender:0b,move:"break",part:"left_arm",armor:10,power:5,activated:1b,version:1}}
replaceitem entity @s[scores={MedapartType=8,Time=92..,Drop=0}] hotbar.2 minecraft:fishing_rod{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:59,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.yuchitang_plus_diver\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"10\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.yuchitang\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.yuchitang_plus_diver.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.yuchitang_plus_diver.model\"}"]},medabots_server:{id:"medabots_server:yuchitang_plus_diver",gender:0b,move:"break",part:"right_arm",armor:10,power:5,activated:1b,version:1}}
replaceitem entity @s[scores={MedapartType=9,Time=92..,Drop=0}] hotbar.3 minecraft:fishing_rod{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:59,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.yuchitang_power_diver\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.break.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"4\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.male\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.yuchitang\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.yuchitang_power_diver.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.yuchitang_power_diver.model\"}"]},medabots_server:{id:"medabots_server:yuchitang_power_diver",gender:0b,move:"break",part:"head",armor:40,power:5,uses:4,activated:1b,version:1}}

# Finish move
scoreboard players reset @s[scores={Break=1,Time=92..},nbt={Inventory:[{Slot:1b,tag:{medabots_server:{part:"left_arm"}}}]}] Break
scoreboard players reset @s[scores={Break=2,Time=92..},nbt={Inventory:[{Slot:3b,tag:{medabots_server:{part:"right_arm"}}}]}] Break
scoreboard players reset @s[scores={Break=3,Time=92..},nbt={Inventory:[{Slot:2b,tag:{medabots_server:{part:"head"}}}]}] Break
scoreboard players reset @s[scores={Break=1..,Time=92..},type=!minecraft:player] Break
execute unless entity @s[scores={Break=1..}] run scoreboard players reset @s MedapartType
execute unless entity @s[scores={Break=1..}] run scoreboard players set @s Time 1

# Attacked by shooting trap
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=!ally_team,tag=!enemy_team] run effect give @s[tag=!undead] minecraft:instant_damage 1 0 true
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=!ally_team,tag=!enemy_team] run effect give @s[tag=undead] minecraft:instant_health 1 0 true
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=!ally_team,tag=!enemy_team] if entity @s[scores={Death=1..},type=minecraft:player] run tellraw @a {"translate":"medabots_server:death.shooting_trap","with":[{"selector":"@s"}]}
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=!ally_team,tag=!enemy_team] run tag @s[scores={Death=1..}] add had_death
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=!ally_team,tag=!enemy_team] run playsound medabots_server:entity.medabot.attack.trap_hit player @a ~ ~ ~ 1
kill @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=!ally_team,tag=!enemy_team]
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=ally_team] run effect give @s[tag=!undead,tag=!ally_medabot] minecraft:instant_damage 1 0 true
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=ally_team] run effect give @s[tag=undead,tag=!ally_medabot] minecraft:instant_health 1 0 true
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=ally_team] if entity @s[scores={Death=1..},type=minecraft:player,tag=!ally_medabot] run tellraw @a {"translate":"medabots_server:death.shooting_trap","with":[{"selector":"@s"}]}
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=ally_team] run tag @s[scores={Death=1..},tag=!ally_medabot] add had_death
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=ally_team] if entity @s[tag=!ally_medabot] run playsound medabots_server:entity.medabot.attack.trap_hit player @a ~ ~ ~ 1
kill @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=ally_team]
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=enemy_team] run effect give @s[tag=!undead,tag=!enemy_medabot] minecraft:instant_damage 1 0 true
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=enemy_team] run effect give @s[tag=undead,tag=!enemy_medabot] minecraft:instant_health 1 0 true
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=enemy_team] if entity @s[scores={Death=1..},type=minecraft:player,tag=!enemy_medabot] run tellraw @a {"translate":"medabots_server:death.shooting_trap","with":[{"selector":"@s"}]}
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=enemy_team] run tag @s[scores={Death=1..},tag=!enemy_medabot] add had_death
execute if entity @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=enemy_team] if entity @s[tag=!enemy_medabot] run playsound medabots_server:entity.medabot.attack.trap_hit player @a ~ ~ ~ 1
kill @e[distance=..3,type=minecraft:area_effect_cloud,tag=shooting_trap,tag=enemy_team]