execute if entity @s[nbt={SelectedItem:{tag:{medabots_server:{part:"tinpet",items:{medal:{tag:{medabots_server:{part:"medal"}}},head:{tag:{medabots_server:{part:"head"}}},right_arm:{tag:{medabots_server:{part:"right_arm"}}},left_arm:{tag:{medabots_server:{part:"left_arm"}}},legs:{tag:{medabots_server:{part:"legs"}}}}}}}}] run tag @s add valid_tinpet
tellraw @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] {"translate":"medabots_server:message.stage.player.enemy","color":"green"}
execute if entity @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] run tellraw @a {"translate":"medabots_server:message.stage.players.0","color":"green","with":[{"translate":"medabots_server:location.final_destination_1"}]}
execute if entity @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] run data merge block -2016 44 -195 {Text1:'{"text":"","clickEvent":{"action":"run_command","value":"function medabots_server:stage/sign/generic/no_pvp_on"}}'}
execute if entity @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] run setblock -2014 45 -195 minecraft:red_wool
execute if entity @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] run data merge block -2016 44 -197 {Text1:'{"text":"","clickEvent":{"action":"run_command","value":"function medabots_server:stage/try/final_destination_1/enter"}}',Text3:'{"translate":"medabots_server:sign.stage.play.main_player"}'}
execute if entity @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] run setblock -2014 45 -197 minecraft:red_wool
tag @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] add enemy_medabot
scoreboard players set @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] StageVersion 1
tag @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] add 0
execute if entity @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] run function medabots_server:gamemodes/default/set_stats
execute if entity @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] run function medabots_server:stage/create/final_destination_1/empty
execute unless entity @s[tag=valid_tinpet,scores={Dialog=0},advancements={medabots_server:special_items/passes/smash_bros=true}] run tellraw @s {"translate":"medabots_server:message.stage.requires.not_matching","with":[{"translate":"medabots_server:message.stage.requirements.final_destination_1.0"}]}
tellraw @s[scores={Dialog=1..}] {"translate":"medabots_server:message.stage.dialog","color":"green"}
tellraw @s[tag=!valid_tinpet] {"translate":"medabots_server:message.tinpet.not_valid"}
tag @s remove valid_tinpet