execute if entity @s[scores={Stage=36,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_1/empty
execute if entity @s[scores={Stage=37,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_2/empty
execute if entity @s[scores={Stage=38,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_3/empty
execute if entity @s[scores={Stage=39,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_4/empty
execute if entity @s[scores={Stage=39,StageVersion=2}] run function medabots_server:stage/enemy_run/lagdou_ruins_4/darkness
execute if entity @s[scores={Stage=40,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_5/empty
execute if entity @s[scores={Stage=40,StageVersion=2}] run function medabots_server:stage/enemy_run/lagdou_ruins_5/darkness
execute if entity @s[scores={Stage=41,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_6/empty
execute if entity @s[scores={Stage=41,StageVersion=2}] run function medabots_server:stage/enemy_run/lagdou_ruins_6/darkness
execute if entity @s[scores={Stage=42,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_7/empty
execute if entity @s[scores={Stage=42,StageVersion=2}] run function medabots_server:stage/enemy_run/lagdou_ruins_7/darkness
execute if entity @s[scores={Stage=43,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_8/empty
execute if entity @s[scores={Stage=43,StageVersion=2}] run function medabots_server:stage/enemy_run/lagdou_ruins_8/darkness
execute if entity @s[scores={Stage=44,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_9/empty
execute if entity @s[scores={Stage=44,StageVersion=2}] run function medabots_server:stage/enemy_run/lagdou_ruins_9/darkness
execute if entity @s[scores={Stage=45,StageVersion=1}] run function medabots_server:stage/enemy_run/lagdou_ruins_10/empty
execute if entity @s[scores={Stage=46,StageVersion=1}] run function medabots_server:stage/enemy_run/ricco_harbor/empty
execute if entity @s[scores={Stage=47,StageVersion=1}] run function medabots_server:stage/enemy_run/woods_battle/stones
execute if entity @s[scores={Stage=47,StageVersion=2}] run function medabots_server:stage/enemy_run/woods_battle/action_floors_1
execute if entity @s[scores={Stage=47,StageVersion=3}] run function medabots_server:stage/enemy_run/woods_battle/action_floors_2
execute if entity @s[scores={Stage=47,StageVersion=4}] run function medabots_server:stage/enemy_run/woods_battle/balloon_bombs
execute if entity @s[scores={Stage=47,StageVersion=5}] run function medabots_server:stage/enemy_run/woods_battle/accelerators
execute if entity @s[scores={Stage=47,StageVersion=6}] run function medabots_server:stage/enemy_run/woods_battle/lasers
execute if entity @s[scores={Stage=47,StageVersion=7}] run function medabots_server:stage/enemy_run/woods_battle/cannons
execute if entity @s[scores={Stage=47,StageVersion=8}] run function medabots_server:stage/enemy_run/woods_battle/empty
execute if entity @s[scores={Stage=48,StageVersion=1}] run function medabots_server:stage/enemy_run/icefield_battle/balloon_bombs
execute if entity @s[scores={Stage=48,StageVersion=2}] run function medabots_server:stage/enemy_run/icefield_battle/mirrors
execute if entity @s[scores={Stage=48,StageVersion=3}] run function medabots_server:stage/enemy_run/icefield_battle/cannons
execute if entity @s[scores={Stage=48,StageVersion=4}] run function medabots_server:stage/enemy_run/icefield_battle/locked_out
execute if entity @s[scores={Stage=48,StageVersion=5}] run function medabots_server:stage/enemy_run/icefield_battle/accelerators
execute if entity @s[scores={Stage=48,StageVersion=6}] run function medabots_server:stage/enemy_run/icefield_battle/ice_blocks
execute if entity @s[scores={Stage=48,StageVersion=7}] run function medabots_server:stage/enemy_run/icefield_battle/spring_walls
execute if entity @s[scores={Stage=48,StageVersion=8}] run function medabots_server:stage/enemy_run/icefield_battle/empty
execute if entity @s[scores={Stage=49,StageVersion=1}] run function medabots_server:stage/enemy_run/ruins_battle/walls
execute if entity @s[scores={Stage=49,StageVersion=2}] run function medabots_server:stage/enemy_run/ruins_battle/wind
execute if entity @s[scores={Stage=49,StageVersion=3}] run function medabots_server:stage/enemy_run/ruins_battle/cannons
execute if entity @s[scores={Stage=49,StageVersion=4}] run function medabots_server:stage/enemy_run/ruins_battle/accelerators
execute if entity @s[scores={Stage=49,StageVersion=5}] run function medabots_server:stage/enemy_run/ruins_battle/lasers
execute if entity @s[scores={Stage=49,StageVersion=6}] run function medabots_server:stage/enemy_run/ruins_battle/hammer_punches
execute if entity @s[scores={Stage=49,StageVersion=7}] run function medabots_server:stage/enemy_run/ruins_battle/locked_in
execute if entity @s[scores={Stage=49,StageVersion=8}] run function medabots_server:stage/enemy_run/ruins_battle/empty
execute if entity @s[scores={Stage=50,StageVersion=1}] run function medabots_server:stage/enemy_run/park_battle/cannons_1
execute if entity @s[scores={Stage=50,StageVersion=2}] run function medabots_server:stage/enemy_run/park_battle/walls
execute if entity @s[scores={Stage=50,StageVersion=3}] run function medabots_server:stage/enemy_run/park_battle/accelerators
execute if entity @s[scores={Stage=50,StageVersion=4}] run function medabots_server:stage/enemy_run/park_battle/wind_1
execute if entity @s[scores={Stage=50,StageVersion=5}] run function medabots_server:stage/enemy_run/park_battle/cannons_2
execute if entity @s[scores={Stage=50,StageVersion=6}] run function medabots_server:stage/enemy_run/park_battle/balloon_bombs
execute if entity @s[scores={Stage=50,StageVersion=7}] run function medabots_server:stage/enemy_run/park_battle/action_floors
execute if entity @s[scores={Stage=50,StageVersion=8}] run function medabots_server:stage/enemy_run/park_battle/wind_2
execute if entity @s[scores={Stage=61,StageVersion=1}] run function medabots_server:stage/enemy_run/final_destination_1/empty
execute if entity @s[scores={Stage=62,StageVersion=1}] run function medabots_server:stage/enemy_run/final_destination_2/empty
execute if entity @s[scores={Stage=63,StageVersion=1}] run function medabots_server:stage/enemy_run/final_destination_3/empty
execute if entity @s[scores={Stage=64,StageVersion=1}] run function medabots_server:stage/enemy_run/final_destination_4/empty