# Move to spectator area
execute if entity @s[scores={Stage=1},tag=first_go] run function medabots_server:stage/leave_stage/grassland_a/first_go
execute if entity @s[scores={Stage=1},tag=second_go] run function medabots_server:stage/leave_stage/grassland_a/second_go
execute if entity @s[scores={Stage=1},tag=rubberobo] run function medabots_server:stage/leave_stage/grassland_a/rubberobo
execute if entity @s[scores={Stage=1},tag=special] run function medabots_server:stage/leave_stage/grassland_a/special
execute if entity @s[scores={Stage=1},tag=object_test] run function medabots_server:stage/leave_stage/grassland_a/object_test
execute if entity @s[scores={Stage=2},tag=first_go] run function medabots_server:stage/leave_stage/rock_a/first_go
execute if entity @s[scores={Stage=2},tag=second_go] run function medabots_server:stage/leave_stage/rock_a/second_go
execute if entity @s[scores={Stage=2},tag=rubberobo] run function medabots_server:stage/leave_stage/rock_a/rubberobo
execute if entity @s[scores={Stage=3},tag=first_go] run function medabots_server:stage/leave_stage/jungle_a/first_go
execute if entity @s[scores={Stage=3},tag=second_go] run function medabots_server:stage/leave_stage/jungle_a/second_go
execute if entity @s[scores={Stage=3},tag=rubberobo] run function medabots_server:stage/leave_stage/jungle_a/rubberobo
execute if entity @s[scores={Stage=4},tag=first_go] run function medabots_server:stage/leave_stage/seashore_a/first_go
execute if entity @s[scores={Stage=4},tag=second_go] run function medabots_server:stage/leave_stage/seashore_a/second_go
execute if entity @s[scores={Stage=4},tag=rubberobo] run function medabots_server:stage/leave_stage/seashore_a/rubberobo
execute if entity @s[scores={Stage=5},tag=first_go] run function medabots_server:stage/leave_stage/snowfield_a/first_go
execute if entity @s[scores={Stage=5},tag=second_go] run function medabots_server:stage/leave_stage/snowfield_a/second_go
execute if entity @s[scores={Stage=5},tag=rubberobo] run function medabots_server:stage/leave_stage/snowfield_a/rubberobo
execute if entity @s[scores={Stage=6},tag=first_go] run function medabots_server:stage/leave_stage/iceberg_a/first_go
execute if entity @s[scores={Stage=6},tag=second_go] run function medabots_server:stage/leave_stage/iceberg_a/second_go
execute if entity @s[scores={Stage=6},tag=rubberobo] run function medabots_server:stage/leave_stage/iceberg_a/rubberobo
execute if entity @s[scores={Stage=7},tag=first_go] run function medabots_server:stage/leave_stage/ruins_out_a/first_go
execute if entity @s[scores={Stage=7},tag=second_go] run function medabots_server:stage/leave_stage/ruins_out_a/second_go
execute if entity @s[scores={Stage=7},tag=rubberobo] run function medabots_server:stage/leave_stage/ruins_out_a/rubberobo
execute if entity @s[scores={Stage=8},tag=first_go] run function medabots_server:stage/leave_stage/ruins_in_a/first_go
execute if entity @s[scores={Stage=8},tag=second_go] run function medabots_server:stage/leave_stage/ruins_in_a/second_go
execute if entity @s[scores={Stage=8},tag=rubberobo] run function medabots_server:stage/leave_stage/ruins_in_a/rubberobo
execute if entity @s[scores={Stage=9},tag=first_go] run function medabots_server:stage/leave_stage/laboratory_a/first_go
execute if entity @s[scores={Stage=9},tag=second_go] run function medabots_server:stage/leave_stage/laboratory_a/second_go
execute if entity @s[scores={Stage=9},tag=rubberobo] run function medabots_server:stage/leave_stage/laboratory_a/rubberobo
execute if entity @s[scores={Stage=10},tag=first_go] run function medabots_server:stage/leave_stage/grassland_b/first_go
execute if entity @s[scores={Stage=10},tag=second_go] run function medabots_server:stage/leave_stage/grassland_b/second_go
execute if entity @s[scores={Stage=11},tag=first_go] run function medabots_server:stage/leave_stage/rock_b/first_go
execute if entity @s[scores={Stage=11},tag=second_go] run function medabots_server:stage/leave_stage/rock_b/second_go
execute if entity @s[scores={Stage=11},tag=rubberobo] run function medabots_server:stage/leave_stage/rock_b/rubberobo
execute if entity @s[scores={Stage=12},tag=first_go] run function medabots_server:stage/leave_stage/jungle_b/first_go
execute if entity @s[scores={Stage=12},tag=second_go] run function medabots_server:stage/leave_stage/jungle_b/second_go
execute if entity @s[scores={Stage=12},tag=rubberobo] run function medabots_server:stage/leave_stage/jungle_b/rubberobo
execute if entity @s[scores={Stage=13},tag=first_go] run function medabots_server:stage/leave_stage/seashore_b/first_go
execute if entity @s[scores={Stage=13},tag=second_go] run function medabots_server:stage/leave_stage/seashore_b/second_go
execute if entity @s[scores={Stage=13},tag=rubberobo] run function medabots_server:stage/leave_stage/seashore_b/rubberobo
execute if entity @s[scores={Stage=13},tag=special] run function medabots_server:stage/leave_stage/seashore_b/special
execute if entity @s[scores={Stage=14},tag=first_go] run function medabots_server:stage/leave_stage/snowfield_b/first_go
execute if entity @s[scores={Stage=14},tag=second_go] run function medabots_server:stage/leave_stage/snowfield_b/second_go
execute if entity @s[scores={Stage=14},tag=rubberobo] run function medabots_server:stage/leave_stage/snowfield_b/rubberobo
execute if entity @s[scores={Stage=14},tag=special] run function medabots_server:stage/leave_stage/snowfield_b/special
execute if entity @s[scores={Stage=15},tag=first_go] run function medabots_server:stage/leave_stage/iceberg_b/first_go
execute if entity @s[scores={Stage=15},tag=second_go] run function medabots_server:stage/leave_stage/iceberg_b/second_go
execute if entity @s[scores={Stage=16},tag=first_go] run function medabots_server:stage/leave_stage/ruins_out_b/first_go
execute if entity @s[scores={Stage=16},tag=second_go] run function medabots_server:stage/leave_stage/ruins_out_b/second_go
execute if entity @s[scores={Stage=16},tag=rubberobo] run function medabots_server:stage/leave_stage/ruins_out_b/rubberobo
execute if entity @s[scores={Stage=16},tag=special] run function medabots_server:stage/leave_stage/ruins_out_b/special
execute if entity @s[scores={Stage=17},tag=first_go] run function medabots_server:stage/leave_stage/ruins_in_b/first_go
execute if entity @s[scores={Stage=17},tag=second_go] run function medabots_server:stage/leave_stage/ruins_in_b/second_go
execute if entity @s[scores={Stage=17},tag=rubberobo] run function medabots_server:stage/leave_stage/ruins_in_b/rubberobo
execute if entity @s[scores={Stage=18},tag=first_go] run function medabots_server:stage/leave_stage/laboratory_b/first_go
execute if entity @s[scores={Stage=18},tag=second_go] run function medabots_server:stage/leave_stage/laboratory_b/second_go
execute if entity @s[scores={Stage=18},tag=rubberobo] run function medabots_server:stage/leave_stage/laboratory_b/rubberobo
execute if entity @s[scores={Stage=18},tag=special] run function medabots_server:stage/leave_stage/laboratory_b/special
execute if entity @s[scores={Stage=19},tag=first_go] run function medabots_server:stage/leave_stage/park_a/first_go
execute if entity @s[scores={Stage=19},tag=second_go] run function medabots_server:stage/leave_stage/park_a/second_go
execute if entity @s[scores={Stage=19},tag=special] run function medabots_server:stage/leave_stage/park_a/special
execute if entity @s[scores={Stage=20},tag=first_go] run function medabots_server:stage/leave_stage/park_b/first_go
execute if entity @s[scores={Stage=20},tag=second_go] run function medabots_server:stage/leave_stage/park_b/second_go
execute if entity @s[scores={Stage=21},tag=first_go] run function medabots_server:stage/leave_stage/paradise_a/first_go
execute if entity @s[scores={Stage=21},tag=second_go] run function medabots_server:stage/leave_stage/paradise_a/second_go
execute if entity @s[scores={Stage=22},tag=first_go] run function medabots_server:stage/leave_stage/paradise_b/first_go
execute if entity @s[scores={Stage=22},tag=second_go] run function medabots_server:stage/leave_stage/paradise_b/second_go
execute if entity @s[scores={Stage=23},tag=first_go] run function medabots_server:stage/leave_stage/grassland_c/first_go
execute if entity @s[scores={Stage=23},tag=second_go] run function medabots_server:stage/leave_stage/grassland_c/second_go
execute if entity @s[scores={Stage=24},tag=first_go] run function medabots_server:stage/leave_stage/jungle_c/first_go
execute if entity @s[scores={Stage=24},tag=second_go] run function medabots_server:stage/leave_stage/jungle_c/second_go
execute if entity @s[scores={Stage=25},tag=first_go] run function medabots_server:stage/leave_stage/seashore_c/first_go
execute if entity @s[scores={Stage=25},tag=second_go] run function medabots_server:stage/leave_stage/seashore_c/second_go
execute if entity @s[scores={Stage=26},tag=first_go] run function medabots_server:stage/leave_stage/iceberg_c/first_go
execute if entity @s[scores={Stage=26},tag=second_go] run function medabots_server:stage/leave_stage/iceberg_c/second_go
execute if entity @s[scores={Stage=27},tag=first_go] run function medabots_server:stage/leave_stage/ruins_out_c/first_go
execute if entity @s[scores={Stage=27},tag=second_go] run function medabots_server:stage/leave_stage/ruins_out_c/second_go
execute if entity @s[scores={Stage=28},tag=first_go] run function medabots_server:stage/leave_stage/laboratory_c/first_go
execute if entity @s[scores={Stage=28},tag=second_go] run function medabots_server:stage/leave_stage/laboratory_c/second_go
execute if entity @s[scores={Stage=29},tag=first_go] run function medabots_server:stage/leave_stage/boxer/first_go
execute if entity @s[scores={Stage=29},tag=second_go] run function medabots_server:stage/leave_stage/boxer/second_go
execute if entity @s[scores={Stage=30},tag=first_go] run function medabots_server:stage/leave_stage/grassland_d/first_go
execute if entity @s[scores={Stage=30},tag=second_go] run function medabots_server:stage/leave_stage/grassland_d/second_go
execute if entity @s[scores={Stage=31},tag=first_go] run function medabots_server:stage/leave_stage/jungle_d/first_go
execute if entity @s[scores={Stage=31},tag=second_go] run function medabots_server:stage/leave_stage/jungle_d/second_go
execute if entity @s[scores={Stage=32},tag=first_go] run function medabots_server:stage/leave_stage/snowfield_d/first_go
execute if entity @s[scores={Stage=32},tag=second_go] run function medabots_server:stage/leave_stage/snowfield_d/second_go
execute if entity @s[scores={Stage=33},tag=first_go] run function medabots_server:stage/leave_stage/iceberg_d/first_go
execute if entity @s[scores={Stage=33},tag=second_go] run function medabots_server:stage/leave_stage/iceberg_d/second_go
execute if entity @s[scores={Stage=34},tag=first_go] run function medabots_server:stage/leave_stage/ruins_in_d/first_go
execute if entity @s[scores={Stage=34},tag=second_go] run function medabots_server:stage/leave_stage/ruins_in_d/second_go
execute if entity @s[scores={Stage=35},tag=first_go] run function medabots_server:stage/leave_stage/laboratory_d/first_go
execute if entity @s[scores={Stage=35},tag=second_go] run function medabots_server:stage/leave_stage/laboratory_d/second_go
execute if entity @s[scores={Stage=36},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_1/empty
execute if entity @s[scores={Stage=37},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_2/empty
execute if entity @s[scores={Stage=38},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_3/empty
execute if entity @s[scores={Stage=39},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_4/empty
execute if entity @s[scores={Stage=39},tag=darkness] run function medabots_server:stage/leave_stage/lagdou_ruins_4/darkness
execute if entity @s[scores={Stage=40},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_5/empty
execute if entity @s[scores={Stage=40},tag=darkness] run function medabots_server:stage/leave_stage/lagdou_ruins_5/darkness
execute if entity @s[scores={Stage=41},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_6/empty
execute if entity @s[scores={Stage=41},tag=darkness] run function medabots_server:stage/leave_stage/lagdou_ruins_6/darkness
execute if entity @s[scores={Stage=42},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_7/empty
execute if entity @s[scores={Stage=42},tag=darkness] run function medabots_server:stage/leave_stage/lagdou_ruins_7/darkness
execute if entity @s[scores={Stage=43},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_8/empty
execute if entity @s[scores={Stage=43},tag=darkness] run function medabots_server:stage/leave_stage/lagdou_ruins_8/darkness
execute if entity @s[scores={Stage=44},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_9/empty
execute if entity @s[scores={Stage=44},tag=darkness] run function medabots_server:stage/leave_stage/lagdou_ruins_9/darkness
execute if entity @s[scores={Stage=45},tag=empty] run function medabots_server:stage/leave_stage/lagdou_ruins_10/empty
execute if entity @s[scores={Stage=46},tag=empty] run function medabots_server:stage/leave_stage/ricco_harbor/empty
execute if entity @s[scores={Stage=47},tag=stones] run function medabots_server:stage/leave_stage/woods_battle/stones
execute if entity @s[scores={Stage=47},tag=action_floors_1] run function medabots_server:stage/leave_stage/woods_battle/action_floors_1
execute if entity @s[scores={Stage=47},tag=action_floors_2] run function medabots_server:stage/leave_stage/woods_battle/action_floors_2
execute if entity @s[scores={Stage=47},tag=balloon_bombs] run function medabots_server:stage/leave_stage/woods_battle/balloon_bombs
execute if entity @s[scores={Stage=47},tag=accelerators] run function medabots_server:stage/leave_stage/woods_battle/accelerators
execute if entity @s[scores={Stage=47},tag=lasers] run function medabots_server:stage/leave_stage/woods_battle/lasers
execute if entity @s[scores={Stage=47},tag=cannons] run function medabots_server:stage/leave_stage/woods_battle/cannons
execute if entity @s[scores={Stage=47},tag=empty] run function medabots_server:stage/leave_stage/woods_battle/empty
execute if entity @s[scores={Stage=48},tag=balloon_bombs] run function medabots_server:stage/leave_stage/icefield_battle/balloon_bombs
execute if entity @s[scores={Stage=48},tag=mirrors] run function medabots_server:stage/leave_stage/icefield_battle/mirrors
execute if entity @s[scores={Stage=48},tag=cannons] run function medabots_server:stage/leave_stage/icefield_battle/cannons
execute if entity @s[scores={Stage=48},tag=locked_out] run function medabots_server:stage/leave_stage/icefield_battle/locked_out
execute if entity @s[scores={Stage=48},tag=accelerators] run function medabots_server:stage/leave_stage/icefield_battle/accelerators
execute if entity @s[scores={Stage=48},tag=ice_blocks] run function medabots_server:stage/leave_stage/icefield_battle/ice_blocks
execute if entity @s[scores={Stage=48},tag=spring_walls] run function medabots_server:stage/leave_stage/icefield_battle/spring_walls
execute if entity @s[scores={Stage=48},tag=empty] run function medabots_server:stage/leave_stage/icefield_battle/empty
execute if entity @s[scores={Stage=49},tag=walls] run function medabots_server:stage/leave_stage/ruins_battle/walls
execute if entity @s[scores={Stage=49},tag=wind] run function medabots_server:stage/leave_stage/ruins_battle/wind
execute if entity @s[scores={Stage=49},tag=cannons] run function medabots_server:stage/leave_stage/ruins_battle/cannons
execute if entity @s[scores={Stage=49},tag=accelerators] run function medabots_server:stage/leave_stage/ruins_battle/accelerators
execute if entity @s[scores={Stage=49},tag=lasers] run function medabots_server:stage/leave_stage/ruins_battle/lasers
execute if entity @s[scores={Stage=49},tag=hammer_punches] run function medabots_server:stage/leave_stage/ruins_battle/hammer_punches
execute if entity @s[scores={Stage=49},tag=locked_in] run function medabots_server:stage/leave_stage/ruins_battle/locked_in
execute if entity @s[scores={Stage=49},tag=empty] run function medabots_server:stage/leave_stage/ruins_battle/empty
execute if entity @s[scores={Stage=50},tag=cannons_1] run function medabots_server:stage/leave_stage/park_battle/cannons_1
execute if entity @s[scores={Stage=50},tag=walls] run function medabots_server:stage/leave_stage/park_battle/walls
execute if entity @s[scores={Stage=50},tag=accelerators] run function medabots_server:stage/leave_stage/park_battle/accelerators
execute if entity @s[scores={Stage=50},tag=wind_1] run function medabots_server:stage/leave_stage/park_battle/wind_1
execute if entity @s[scores={Stage=50},tag=cannons_2] run function medabots_server:stage/leave_stage/park_battle/cannons_2
execute if entity @s[scores={Stage=50},tag=balloon_bombs] run function medabots_server:stage/leave_stage/park_battle/balloon_bombs
execute if entity @s[scores={Stage=50},tag=action_floors] run function medabots_server:stage/leave_stage/park_battle/action_floors
execute if entity @s[scores={Stage=50},tag=wind_2] run function medabots_server:stage/leave_stage/park_battle/wind_2
execute if entity @s[scores={Stage=51},tag=wave_1] run function medabots_server:stage/leave_stage/mt_battle/wave_1
execute if entity @s[scores={Stage=51},tag=player] run function medabots_server:stage/leave_stage/mt_battle/player