# mission text
execute unless entity @s[scores={Dialog=0..}] run scoreboard players set @s Dialog 0
scoreboard players add @s[scores={Dialog=..80}] Dialog 1
execute if entity @s[scores={Dialog=8}] as @a[tag=hostile] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission","color":"green"}
execute if entity @s[scores={Dialog=32},tag=destroy_all_cannons] as @a[tag=hostile,tag=!enemy_medabot] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.cannons","color":"green"}
execute if entity @s[scores={Dialog=32},tag=destroy_all_cannons] as @a[tag=hostile,tag=enemy_medabot] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.cannons.enemy","color":"green"}
execute if entity @s[scores={Dialog=32},tag=defeat_all_guards] as @a[tag=hostile,tag=!enemy_medabot] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.guards","color":"green"}
execute if entity @s[scores={Dialog=32},tag=defeat_all_guards] as @a[tag=hostile,tag=enemy_medabot] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.guards.enemy","color":"green"}
execute if entity @s[scores={Dialog=32},tag=run_until_the_time_is_up] as @a[tag=hostile,tag=!enemy_medabot] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.time","color":"green"}
execute if entity @s[scores={Dialog=32},tag=run_until_the_time_is_up] as @a[tag=hostile,tag=enemy_medabot] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.time.enemy","color":"green"}
execute if entity @s[scores={Dialog=32},tag=open_the_exit_door] as @a[tag=hostile,tag=!enemy_medabot] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.door","color":"green"}
execute if entity @s[scores={Dialog=32},tag=open_the_exit_door] as @a[tag=hostile,tag=enemy_medabot] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.door.enemy","color":"green"}
execute if entity @s[scores={Dialog=32},tag=defeat_the_enemy] as @a[tag=hostile] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.enemy","color":"green"}
execute if entity @s[scores={Dialog=32},tag=defeat_all_enemies] as @a[tag=hostile] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run title @s title {"translate":"medabots_server:message.stage.mission.enemy.more","color":"green"}
execute if entity @s[scores={Dialog=80}] as @a[tag=hostile] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run scoreboard players set @s Battle 1
execute if entity @s[scores={Dialog=80}] as @e[tag=hostile,tag=enemy_medabot] if score @s Stage = @e[distance=..0.1,tag=mission,limit=1] Stage run scoreboard players set @s Battle 1