tellraw @s {"translate":"medabots_server:message.stage.description.jungle_b"}
tellraw @s {"translate":"medabots_server:message.stage.requires"}
tellraw @s {"translate":"medabots_server:sign.stage.first_go","extra":[{"translate":"medabots_server:message.stage.requires.version"},{"translate":"medabots_server:message.stage.requires.wins.1","with":[{"translate":"medabots_server:location.rock","with":[{"text":"B"}]}]}]}
tellraw @s {"translate":"medabots_server:sign.stage.second_go","extra":[{"translate":"medabots_server:message.stage.requires.version"},{"translate":"medabots_server:message.stage.requires.wins.1","with":[{"translate":"medabots_server:location.jungle","with":[{"text":"B"}]}]}]}
tellraw @s {"translate":"medabots_server:sign.stage.rubberobo","extra":[{"translate":"medabots_server:message.stage.requires.version"},{"translate":"medabots_server:advancements.passes.robo_2"}]}
tellraw @s {"text":""}
tellraw @s {"translate":"medabots_server:message.stage.score.version","with":[{"translate":"medabots_server:sign.stage.second_go"}]}
tellraw @s {"translate":"medabots_server:message.stage.score.calculate","extra":[{"translate":"medabots_server:message.stage.score.time"},{"text":"\n"},{"translate":"medabots_server:message.stage.score.damage"},{"text":"\n"},{"translate":"medabots_server:message.stage.score.money","with":[{"text":"???"}]}]}
tellraw @s {"translate":"medabots_server:message.stage.score.best"}
tellraw @s {"translate":"medabots_server:message.stage.score.scoreholder","with":[{"text":"0"},{"translate":"medabots_server:message.stage.score.no_scoreholder"},{"translate":"medabots_server:message.stage.score.no_scoreholder.yet"}]}