tellraw @s {"translate":"medabots_server:message.stage.description.medium_fly_course_1"}
tellraw @s {"translate":"medabots_server:message.stage.score.fly_course.normal"}
tellraw @s {"translate":"medabots_server:message.stage.score.calculate","extra":[{"translate":"medabots_server:message.stage.score.rings"}]}
tellraw @s {"translate":"medabots_server:message.stage.score.best"}
tellraw @s {"translate":"medabots_server:message.stage.score.scoreholder","with":[{"text":"1"},{"text":"FVbico"},{"text":"799"}]}
tellraw @s {"translate":"medabots_server:message.stage.score.scoreholder","with":[{"text":"2"},{"text":"Panda"},{"text":"82"}]}
tellraw @s {"translate":"medabots_server:message.stage.score.scoreholder","with":[{"text":"3"},{"text":"piotrex43"},{"text":"40"}]}
tellraw @s {"translate":"medabots_server:message.stage.score.scoreholder","with":[{"text":"4"},{"text":"_SunCat_"},{"text":"27"}]}
tellraw @s {"translate":"medabots_server:message.stage.score.fly_course.challenge"}
tellraw @s {"translate":"medabots_server:message.stage.score.calculate","extra":[{"translate":"medabots_server:message.stage.score.rings"}]}
tellraw @s {"translate":"medabots_server:message.stage.score.best"}
tellraw @s {"translate":"medabots_server:message.stage.score.scoreholder","with":[{"text":"0"},{"translate":"medabots_server:message.stage.score.no_scoreholder"},{"translate":"medabots_server:message.stage.score.no_scoreholder.yet"}]}