# Knight Armor
summon minecraft:skeleton -1799 44 -259 {CustomName:'{"translate":"medabots_server:entity.knight_armor"}',CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/laboratory_a/first_go/knight_armor",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["knight_armor","enemy_medabot","killerable","hostile","wheel_legs","scout_left_arm","sword_right_arm","defense_head","ghost_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
execute if entity @s[tag=practice_battle] run data merge entity @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor,limit=1] {DeathLootTable:"medabots_server:entities/battle_enemies/practice_round"}
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] Stage 9
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] Medabot 0
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] Charge 0
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] Battle 2
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] MaxHeadUses 8
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] MaxHeadArmor 100
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] MaxRightArmArmor 40
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] MaxLeftArmArmor 65
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] MaxLegsArmor 60
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] HeadPower 52
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] RightArmPower 20
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] LeftArmPower 41
scoreboard players set @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] LegsDefense 32
scoreboard players operation @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] MedabotNr 1
execute as @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1799,y=44,z=-259,distance=..1,tag=knight_armor] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1799 44 -259 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:2,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.knight_armor_troyan_horse"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.wheel"}','{"italic":false,"color":"white","translate":"medabots_server:move.wheel.description"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"60"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.knight_armor"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.knight_armor_troyan_horse.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.knight_armor_troyan_horse.model"}']},medabots_server:{id:"medabots_server:knight_armor_troyan_horse",gender:0b,move:"wheel",part:"legs",armor:60,defense:32,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1799 44 -259 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:3,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.doctor_study_cut_radar"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.scout"}','{"italic":false,"color":"white","translate":"medabots_server:move.scout.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.infinite"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"65"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.doctor_study"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.doctor_study_cut_radar.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.doctor_study_cut_radar.model"}']},medabots_server:{id:"medabots_server:doctor_study_cut_radar",gender:0b,move:"scout",part:"left_arm",armor:65,power:41,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1799 44 -259 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:69,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.nin_ninja_ninja_dagger"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.sword"}','{"italic":false,"color":"white","translate":"medabots_server:move.sword.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.infinite"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"40"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.nin_ninja"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.nin_ninja_ninja_dagger.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.nin_ninja_ninja_dagger.model"}']},medabots_server:{id:"medabots_server:nin_ninja_ninja_dagger",gender:0b,move:"sword",part:"right_arm",armor:40,power:20,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1799 44 -259 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","male_tinpet","medabot_model"],CustomName:'{"translate":"medabots_server:entity.medabot_model"}',ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:2,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.knight_armor_clearshield"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.defense"}','{"italic":false,"color":"white","translate":"medabots_server:move.defense.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.more","with":[{"text":"8"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"100"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.knight_armor"}',"",'{"italic":false,"color":"white","translate":"medabots_server:item.knight_armor_clearshield.quote"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.knight_armor_clearshield.model"}']},medabots_server:{id:"medabots_server:knight_armor_clearshield",gender:0b,move:"defense",part:"head",armor:100,power:52,uses:8,activated:0b,version:1}}}]}
execute positioned -1799 44 -259 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=knight_armor] MedabotNr