# Pastel Fairy
summon minecraft:skeleton -1702 44 -207 {CustomName:"{\"translate\":\"medabots_server:entity.pastel_fairy\"}",CustomNameVisisble:1b,Team:"StageEnemy",ArmorItems:[{},{},{},{id:"minecraft:structure_void",Count:1b}],HandItems:[{},{}],Attributes:[{Name:"generic.maxHealth",Base:100.0d},{Name:"generic.attackDamage",Base:0.0d}],Health:100.0f,DeathLootTable:"medabots_server:entities/iceberg_a/second_go/pastel_fairy",ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],HandDropChances:[0.0f,0.0f],PersistenceRequired:1b,Tags:["pastel_fairy","enemy_medabot","killerable","hostile","float_legs","heal_left_arm","freeze_right_arm","shooting_trap_head","ghost_medal"],AbsorptionAmount:100.0f,ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}]}
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] Stage 18
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] Medabot 0
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] Battle 1
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] MaxHeadUses 12
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] MaxHeadArmor 70
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] MaxRightArmArmor 35
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] MaxLeftArmArmor 40
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] MaxLegsArmor 55
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] HeadPower 43
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] RightArmPower 26
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] LeftArmPower 50
scoreboard players set @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] LegsDefense 29
scoreboard players operation @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] MedabotNr > @e[scores={MedabotNr=0..}] MedabotNr
scoreboard players add @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] MedabotNr 1
execute as @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] run scoreboard players operation @s HeadUses = @s MaxHeadUses
execute as @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] run scoreboard players operation @s HeadArmor = @s MaxHeadArmor
execute as @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] run scoreboard players operation @s RightArmArmor = @s MaxRightArmArmor
execute as @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] run scoreboard players operation @s LeftArmArmor = @s MaxLeftArmArmor
execute as @e[x=-1702,y=44,z=-207,distance=..1,tag=pastel_fairy] run scoreboard players operation @s LegsArmor = @s MaxLegsArmor
summon minecraft:armor_stand -1702 44 -207 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["legs","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:1,Unbreakable:1b,HideFlags:4,CustomModelData:37,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pastel_fairy_flower_fly\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.float\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.float.description\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"55\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.pastel_fairy\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pastel_fairy_flower_fly.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pastel_fairy_flower_fly.model\"}"]},medabots_server:{id:"medabots_server:pastel_fairy_flower_fly",gender:1b,move:"float",part:"legs",armor:55,defense:29,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1702 44 -207 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["left_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:43,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pure_mermaid_repair_arm\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.heal\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.heal.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"40\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.pure_mermaid\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pure_mermaid_repair_arm.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pure_mermaid_repair_arm.model\"}"]},medabots_server:{id:"medabots_server:pure_mermaid_repair_arm",gender:1b,move:"heal",part:"left_arm",armor:40,power:50,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1702 44 -207 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["right_arm","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:3,Unbreakable:1b,HideFlags:4,CustomModelData:68,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.frappe_flap\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.freeze\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.freeze.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.infinite\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"35\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.frappe\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.frappe_flap.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.frappe_flap.model\"}"]},medabots_server:{id:"medabots_server:frappe_flap",gender:1b,move:"freeze",part:"right_arm",armor:35,power:26,activated:0b,version:1}}}]}
summon minecraft:armor_stand -1702 44 -207 {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["head","medabot_model"],CustomName:"{\"translate\":\"medabots_server:entity.medabot_model\"}",ArmorItems:[{},{},{},{id:"minecraft:fishing_rod",Count:1b,tag:{Damage:4,Unbreakable:1b,HideFlags:4,CustomModelData:37,display:{Name:"{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pastel_fairy_field_barrier\"}",Lore:["{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.shooting_trap\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:move.shooting_trap.description\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.uses.more\",\"with\":[{\"text\":\"12\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.armor\",\"with\":[{\"text\":\"70\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.female\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:entity.pastel_fairy\"}","","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pastel_fairy_field_barrier.quote\"}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.part.wave\",\"with\":[{\"text\":\"1\"}]}","{\"italic\":false,\"color\":\"white\",\"translate\":\"medabots_server:item.pastel_fairy_field_barrier.model\"}"]},medabots_server:{id:"medabots_server:pastel_fairy_field_barrier",gender:1b,move:"shooting_trap",part:"head",armor:70,power:43,uses:12,activated:0b,version:1}}}]}
execute positioned -1702 44 -207 as @e[tag=medabot_model,distance=..1] run scoreboard players operation @s MedabotNr = @e[distance=..1,limit=1,tag=pastel_fairy] MedabotNr

# Player
teleport @s -1701 44 -240
function medabots_server:stage/create/iceberg_a/second_go