function medabots_server:give_items/medaparts/aimflash/carrybag
function medabots_server:give_items/medaparts/aimflash/tripod
function medabots_server:give_items/medaparts/aimflash/zoom
function medabots_server:give_items/medaparts/aimflash/strobe