function medabots_server:give_items/medaparts/basstroyer/lakeduster
function medabots_server:give_items/medaparts/basstroyer/srounding
function medabots_server:give_items/medaparts/basstroyer/environment
function medabots_server:give_items/medaparts/basstroyer/great_swallow