function medabots_server:give_items/medaparts/boarbooster/mashglow
function medabots_server:give_items/medaparts/boarbooster/woolybond
function medabots_server:give_items/medaparts/boarbooster/drillril
function medabots_server:give_items/medaparts/boarbooster/boartusk