function medabots_server:give_items/medaparts/darknut/darkarmor
function medabots_server:give_items/medaparts/darknut/darkshield
function medabots_server:give_items/medaparts/darknut/darksword
function medabots_server:give_items/medaparts/darknut/darkhelmet