function medabots_server:give_items/medaparts/fancyroll/bubuhip
function medabots_server:give_items/medaparts/fancyroll/letbomb
function medabots_server:give_items/medaparts/fancyroll/magicalbit
function medabots_server:give_items/medaparts/fancyroll/palrunmannor