function medabots_server:give_items/medaparts/frappe/flavor
function medabots_server:give_items/medaparts/frappe/flop
function medabots_server:give_items/medaparts/frappe/flap
function medabots_server:give_items/medaparts/frappe/flip