function medabots_server:give_items/medaparts/god_emperor/death_crawler
function medabots_server:give_items/medaparts/god_emperor/death_laser
function medabots_server:give_items/medaparts/god_emperor/death_missile
function medabots_server:give_items/medaparts/god_emperor/death_break