function medabots_server:give_items/medaparts/hellphoenix/red_tail
function medabots_server:give_items/medaparts/hellphoenix/flame_gun
function medabots_server:give_items/medaparts/hellphoenix/fire_gun
function medabots_server:give_items/medaparts/hellphoenix/blast_gun