function medabots_server:give_items/medaparts/king_pharaoh/sit_down
function medabots_server:give_items/medaparts/king_pharaoh/dark_hall
function medabots_server:give_items/medaparts/king_pharaoh/black_hall
function medabots_server:give_items/medaparts/king_pharaoh/grand_bomb