function medabots_server:give_items/medaparts/peppercat/quick_alert
function medabots_server:give_items/medaparts/peppercat/light_blow
function medabots_server:give_items/medaparts/peppercat/lightjump
function medabots_server:give_items/medaparts/peppercat/lightcircuit