function medabots_server:give_items/medaparts/saikachis/enplace
function medabots_server:give_items/medaparts/saikachis/blaster
function medabots_server:give_items/medaparts/saikachis/fuser
function medabots_server:give_items/medaparts/saikachis/balister