function medabots_server:give_items/medaparts/sphere_doomers/doomer
function medabots_server:give_items/medaparts/sphere_doomers/fire_doomer
function medabots_server:give_items/medaparts/sphere_doomers/electric_doomer
function medabots_server:give_items/medaparts/sphere_doomers/ice_doomer