function medabots_server:give_items/medaparts/zant/usurper_outfit
function medabots_server:give_items/medaparts/zant/usurper_scimitar
function medabots_server:give_items/medaparts/zant/twilight_scimitar
function medabots_server:give_items/medaparts/zant/zant_helmet