execute positioned -1518 45 -208 run function medabots_server:spawn_entities/guard/slow
execute positioned -1523 45 -202 run function medabots_server:spawn_entities/guard/slow
execute positioned -1537 45 -201 run function medabots_server:spawn_entities/guard/slow
execute positioned -1540 45 -198 run function medabots_server:spawn_entities/guard/slow
execute positioned -1544 45 -200 run function medabots_server:spawn_entities/guard/slow
execute positioned -1548 45 -198 run function medabots_server:spawn_entities/guard/slow
execute positioned -1561 45 -189 run function medabots_server:spawn_entities/guard/slow
execute positioned -1544 45 -213 run function medabots_server:spawn_entities/guard/slow/2_medallar_cents
execute positioned -1540 45 -216 run function medabots_server:spawn_entities/guard/slow/2_medallar_cents
execute positioned -1535 45 -216 run function medabots_server:spawn_entities/guard/slow/6_medallar_cents
execute positioned -1532 45 -224 run function medabots_server:spawn_entities/guard/slow
execute positioned -1526 45 -233 run function medabots_server:spawn_entities/guard/slow
execute positioned -1529 45 -237 run function medabots_server:spawn_entities/guard/slow
execute positioned -1547 45 -237 run function medabots_server:spawn_entities/guard/slow
execute positioned -1567 45 -237 run function medabots_server:spawn_entities/guard/slow
execute positioned -1567 45 -235 run function medabots_server:spawn_entities/guard/slow
execute positioned -1550 45 -231 run function medabots_server:spawn_entities/guard/slow
execute positioned -1546 45 -226 run function medabots_server:spawn_entities/guard/slow
execute positioned -1518 45 -204 run function medabots_server:spawn_entities/cannon/no_detect/looking/south/delay_4/1_medallar_cent
execute positioned -1518 45 -214 run function medabots_server:spawn_entities/cannon/no_detect/rotating/north/delay_4/1_medallar_cent
execute positioned -1534 45 -193 run function medabots_server:spawn_entities/cannon/no_detect/looking/east/delay_4/1_medallar_cent
execute positioned -1541 45 -188 run function medabots_server:spawn_entities/cannon/detect/looking/north/delay_4/1_medallar_cent
execute positioned -1548 45 -192 run function medabots_server:spawn_entities/cannon/detect/looking/east/delay_4/1_medallar_cent
execute positioned -1556 45 -191 run function medabots_server:spawn_entities/cannon/detect/looking/south/delay_4/1_medallar_cent
execute positioned -1559 45 -204 run function medabots_server:spawn_entities/cannon/detect/rotating/south/delay_4/1_medallar_cent
execute positioned -1563 45 -217 run function medabots_server:spawn_entities/cannon/detect/rotating/west/delay_4/1_medallar_cent
execute positioned -1555 45 -214 run function medabots_server:spawn_entities/cannon/detect/rotating/west/delay_4/1_medallar_cent
execute positioned -1527 45 -223 run function medabots_server:spawn_entities/cannon/no_detect/looking/west/delay_4
execute positioned -1525 45 -225 run function medabots_server:spawn_entities/cannon/no_detect/looking/west/delay_4
execute positioned -1522 45 -239 run function medabots_server:spawn_entities/cannon/no_detect/looking/west/delay_4
execute positioned -1524 45 -241 run function medabots_server:spawn_entities/cannon/no_detect/looking/west/delay_4
execute positioned -1536 45 -243 run function medabots_server:spawn_entities/cannon/no_detect/looking/south/delay_4
execute positioned -1538 45 -245 run function medabots_server:spawn_entities/cannon/no_detect/looking/south/delay_4
execute positioned -1540 45 -243 run function medabots_server:spawn_entities/cannon/no_detect/looking/south/delay_4
execute positioned -1551 45 -241 run function medabots_server:spawn_entities/cannon/no_detect/looking/east/delay_4
execute positioned -1553 45 -239 run function medabots_server:spawn_entities/cannon/no_detect/looking/east/delay_4
execute positioned -1555 45 -227 run function medabots_server:spawn_entities/cannon/no_detect/looking/east/delay_4
execute positioned -1553 45 -225 run function medabots_server:spawn_entities/cannon/no_detect/looking/east/delay_4
execute positioned -1565 45 -204 run function medabots_server:spawn_entities/item/2_medallar_cents
execute positioned -1566 45 -210 run function medabots_server:spawn_entities/item/4_medallar_cents
execute positioned -1538 45 -240 run function medabots_server:spawn_entities/item/6_medallar_cents
execute positioned -1549 45 -186 run function medabots_server:set_blocks/floor_switch/green
execute positioned -1537 45 -187 run function medabots_server:set_blocks/floor_switch/green
execute positioned -1551 45 -206 run function medabots_server:set_blocks/floor_switch/green
execute positioned -1556 45 -187 run function medabots_server:set_blocks/floor_switch/green
execute positioned -1534 45 -206 run function medabots_server:set_blocks/floor_switch/blue
execute positioned -1560 45 -204 run function medabots_server:set_blocks/hole/delay_5
execute positioned -1560 45 -205 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1565 45 -204 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1566 45 -210 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1562 45 -218 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1555 45 -213 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1538 45 -237 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1541 45 -239 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1535 45 -240 run function medabots_server:spawn_entities/balloon_bomb
execute positioned -1512 45 -215 run function medabots_server:set_blocks/action_floor/enabled/round_stone/south
execute positioned -1511 45 -218 run function medabots_server:set_blocks/action_floor/enabled/round_stone/south
execute positioned -1517 45 -189 run function medabots_server:set_blocks/pot/2_medallar_cents
execute positioned -1518 45 -188 run function medabots_server:set_blocks/pot/2_medallar_cents
execute positioned -1517 45 -188 run function medabots_server:set_blocks/pot/bomb/delay_5
execute positioned -1517 45 -187 run function medabots_server:set_blocks/pot/2_medallar_cents
execute positioned -1523 45 -187 run function medabots_server:set_blocks/pot/purple_plant
execute positioned -1524 45 -187 run function medabots_server:set_blocks/pot/bomb/delay_5
execute positioned -1537 45 -188 run function medabots_server:set_blocks/pot
execute positioned -1536 45 -187 run function medabots_server:set_blocks/pot
execute positioned -1538 45 -187 run function medabots_server:set_blocks/pot
execute positioned -1537 45 -186 run function medabots_server:set_blocks/pot
execute positioned -1549 45 -187 run function medabots_server:set_blocks/pot
execute positioned -1548 45 -186 run function medabots_server:set_blocks/pot
execute positioned -1550 45 -186 run function medabots_server:set_blocks/pot/guard/slow
execute positioned -1547 45 -207 run function medabots_server:set_blocks/pot
execute positioned -1547 45 -205 run function medabots_server:set_blocks/pot
execute positioned -1548 45 -208 run function medabots_server:set_blocks/pot
execute positioned -1548 45 -206 run function medabots_server:set_blocks/pot/guard/slow
execute positioned -1549 45 -207 run function medabots_server:set_blocks/pot
execute positioned -1549 45 -205 run function medabots_server:set_blocks/pot
execute positioned -1550 45 -208 run function medabots_server:set_blocks/pot
execute positioned -1550 45 -206 run function medabots_server:set_blocks/pot/guard/slow
execute positioned -1551 45 -207 run function medabots_server:set_blocks/pot/6_medallar_cents
execute positioned -1551 45 -205 run function medabots_server:set_blocks/pot/6_medallar_cents
execute positioned -1556 45 -193 run function medabots_server:set_blocks/pot/4_medallar_cents
execute positioned -1565 45 -239 run function medabots_server:set_blocks/pot
execute positioned -1562 45 -235 run function medabots_server:set_blocks/pot
execute positioned -1564 45 -231 run function medabots_server:set_blocks/pot
execute positioned -1567 45 -236 run function medabots_server:set_blocks/pot/6_medallar_cents
execute positioned -1512 45 -230 run function medabots_server:set_blocks/pot/guard/slow
execute positioned -1511 45 -227 run function medabots_server:set_blocks/pot/2_medallar_cents
execute positioned -1513 45 -225 run function medabots_server:set_blocks/pot/2_medallar_cents
execute positioned -1509 45 -225 run function medabots_server:set_blocks/pot
execute positioned -1514 45 -223 run function medabots_server:set_blocks/pot/guard/slow
# Medapart pot
execute positioned -1510 45 -223 run function medabots_server:set_blocks/pot
replaceitem block -1510 45 -223 container.0 minecraft:fishing_rod{Damage:2,Unbreakable:1b,HideFlags:4,CustomModelData:12,display:{Name:'{"italic":false,"color":"white","translate":"medabots_server:item.hellphoenix_flame_gun"}',Lore:['{"italic":false,"color":"white","translate":"medabots_server:move.melt"}','{"italic":false,"color":"white","translate":"medabots_server:move.melt.description"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.uses.infinite"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.armor","with":[{"text":"45"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.part.male"}','{"italic":false,"color":"white","translate":"medabots_server:entity.hellphoenix"}','{"italic":false,"color":"white","translate":"medabots_server:item.part.wave","with":[{"text":"1"}]}','{"italic":false,"color":"white","translate":"medabots_server:item.hellphoenix_flame_gun.model"}']},medabots_server:{stage_item:1b,id:"medabots_server:hellphoenix_flame_gun",gender:0b,move:"melt",part:"left_arm",armor:45,power:22,activated:0b,version:1}}
execute positioned -1511 45 -192 run function medabots_server:set_blocks/bridge
execute positioned -1514 45 -190 run function medabots_server:set_blocks/bridge
execute positioned -1528 45 -193 run function medabots_server:set_blocks/bridge
execute positioned -1529 45 -193 run function medabots_server:set_blocks/bridge
execute positioned -1529 45 -192 run function medabots_server:set_blocks/bridge
execute positioned -1530 45 -192 run function medabots_server:set_blocks/bridge
execute positioned -1553 45 -213 run function medabots_server:set_blocks/bridge
execute positioned -1553 45 -214 run function medabots_server:set_blocks/bridge
execute positioned -1553 45 -215 run function medabots_server:set_blocks/bridge
execute positioned -1552 45 -214 run function medabots_server:set_blocks/bridge
execute positioned -1539 45 -220 run function medabots_server:set_blocks/bridge
execute positioned -1539 45 -221 run function medabots_server:set_blocks/bridge
execute positioned -1551 45 -227 run function medabots_server:set_blocks/bridge
execute positioned -1550 45 -227 run function medabots_server:set_blocks/bridge
execute positioned -1550 45 -238 run function medabots_server:set_blocks/bridge
execute positioned -1549 45 -238 run function medabots_server:set_blocks/bridge
execute positioned -1557 45 -238 run function medabots_server:set_blocks/bridge
execute positioned -1558 45 -238 run function medabots_server:set_blocks/bridge
execute positioned -1559 45 -238 run function medabots_server:set_blocks/bridge
execute positioned -1560 45 -238 run function medabots_server:set_blocks/bridge
execute positioned -1561 45 -238 run function medabots_server:set_blocks/bridge
execute positioned -1562 45 -238 run function medabots_server:set_blocks/bridge
execute positioned -1538 45 -232 run function medabots_server:set_blocks/bridge
execute positioned -1538 45 -233 run function medabots_server:set_blocks/bridge
execute positioned -1526 45 -239 run function medabots_server:set_blocks/bridge
execute positioned -1525 45 -239 run function medabots_server:set_blocks/bridge
execute positioned -1530 45 -225 run function medabots_server:set_blocks/bridge
execute positioned -1529 45 -225 run function medabots_server:set_blocks/bridge
execute positioned -1510 45 -196 run function medabots_server:set_blocks/stone
execute positioned -1513 45 -210 run function medabots_server:set_blocks/stone
execute positioned -1510 45 -214 run function medabots_server:set_blocks/stone
execute positioned -1518 45 -194 run function medabots_server:set_blocks/stone
execute positioned -1517 45 -204 run function medabots_server:set_blocks/stone
execute positioned -1522 45 -204 run function medabots_server:set_blocks/stone
execute positioned -1524 45 -199 run function medabots_server:set_blocks/stone
execute positioned -1522 45 -193 run function medabots_server:set_blocks/stone
execute positioned -1525 45 -188 run function medabots_server:set_blocks/stone
execute positioned -1524 45 -188 run function medabots_server:set_blocks/stone
execute positioned -1523 45 -188 run function medabots_server:set_blocks/stone
execute positioned -1560 45 -197 run function medabots_server:set_blocks/stone
execute positioned -1568 45 -197 run function medabots_server:set_blocks/stone
execute positioned -1567 45 -201 run function medabots_server:set_blocks/stone
execute positioned -1567 45 -204 run function medabots_server:set_blocks/stone
execute positioned -1563 45 -204 run function medabots_server:set_blocks/stone
execute positioned -1557 45 -205 run function medabots_server:set_blocks/stone
execute positioned -1568 45 -210 run function medabots_server:set_blocks/stone
execute positioned -1568 45 -214 run function medabots_server:set_blocks/stone
execute positioned -1567 45 -216 run function medabots_server:set_blocks/stone
execute positioned -1567 45 -218 run function medabots_server:set_blocks/stone
execute positioned -1564 45 -216 run function medabots_server:set_blocks/stone
execute positioned -1562 45 -217 run function medabots_server:set_blocks/stone
execute positioned -1564 45 -210 run function medabots_server:set_blocks/stone
execute positioned -1559 45 -212 run function medabots_server:set_blocks/stone
execute positioned -1556 45 -214 run function medabots_server:set_blocks/stone
execute positioned -1535 45 -190 run function medabots_server:set_blocks/wall
execute positioned -1541 45 -192 run function medabots_server:set_blocks/wall
execute positioned -1546 45 -189 run function medabots_server:set_blocks/wall
execute positioned -1559 45 -209 run function medabots_server:set_blocks/wall
execute positioned -1560 45 -209 run function medabots_server:set_blocks/wall
execute positioned -1550 45 -213 run function medabots_server:set_blocks/accelerator/west
execute positioned -1550 45 -215 run function medabots_server:set_blocks/accelerator/west
execute positioned -1543 45 -215 run function medabots_server:set_blocks/accelerator/west
execute positioned -1533 45 -196 run function medabots_server:set_blocks/door/closed/south
execute positioned -1551 45 -194 run function medabots_server:set_blocks/door/closed/south
execute positioned -1534 45 -207 run function medabots_server:set_blocks/door/closed/south
execute positioned -1569 45 -207 run function medabots_server:set_blocks/door/closed/south
execute positioned -1538 45 -229 run function medabots_server:set_blocks/goal_area
execute positioned -1509 45 -196 run function medabots_server:set_blocks/starting_area
tag @s add second_go
teleport @s -1509 45 -196
bossbar set medabots_server:seashore_a/time value 0
bossbar set medabots_server:seashore_a/time players @s
scoreboard players set @a[x=-1509,y=45,z=-196,distance=..1] Battle 1
scoreboard players set @a[x=-1509,y=45,z=-196,distance=..1] Stage 4
scoreboard players set @a[x=-1509,y=45,z=-196,distance=..1] Music 0
scoreboard players set @a[x=-1509,y=45,z=-196,distance=..1] MusicType 10